(function () {
    pokedex = [
      {id: 0001, name:'Bulbasaur', type1:'Grass', type2:'Poison'},
      {id: 0002, name:'Ivysaur', type1:'Grass', type2:'Poison'},
      {id: 0003, name:'Venusaur', type1:'Grass', type2:'Poison'},
      {id: 0003, name:'Venusaur-Mega', type1:'Grass', type2:'Poison'},
      {id: 0004, name:'Charmander', type1:'Fire', type2:''},
      {id: 0005, name:'Charmeleon', type1:'Fire', type2:''},
      {id: 0006, name:'Charizard', type1:'Fire', type2:'Flying'},
      {id: 0006, name:'Charizard-Mega X', type1:'Fire', type2:'Dragon'},
      {id: 0006, name:'Charizard-Mega Y', type1:'Fire', type2:'Flying'},
      {id: 0007, name:'Squirtle', type1:'Water', type2:''},
      {id: 0008, name:'Wartortle', type1:'Water', type2:''},
      {id: 0009, name:'Blastoise', type1:'Water', type2:''},
      {id: 0009, name:'Blastoise-Mega', type1:'Water', type2:''},
      {id: 0010, name:'Caterpie', type1:'Bug', type2:''},
      {id: 0011, name:'Metapod', type1:'Bug', type2:''},
      {id: 0012, name:'Butterfree', type1:'Bug', type2:'Flying'},
      {id: 0013, name:'Weedle', type1:'Bug', type2:'Poison'},
      {id: 0014, name:'Kakuna', type1:'Bug', type2:'Poison'},
      {id: 0015, name:'Beedrill', type1:'Bug', type2:'Poison'},
      {id: 0015, name:'Beedrill-Mega', type1:'Bug', type2:'Poison'},
      {id: 0016, name:'Pidgey', type1:'Normal', type2:'Flying'},
      {id: 0017, name:'Pidgeotto', type1:'Normal', type2:'Flying'},
      {id: 0018, name:'Pidgeot', type1:'Normal', type2:'Flying'},
      {id: 0018, name:'Pidgeot-Mega', type1:'Normal', type2:'Flying'},
      {id: 0019, name:'Rattata', type1:'Normal', type2:''},
      {id: 0019, name:'Rattata-Alolan', type1:'Dark', type2:'Normal'},
      {id: 0020, name:'Raticate', type1:'Normal', type2:''},
      {id: 0020, name:'Raticate-Alolan', type1:'Dark', type2:'Normal'},
      {id: 0021, name:'Spearow', type1:'Normal', type2:'Flying'},
      {id: 0022, name:'Fearow', type1:'Normal', type2:'Flying'},
      {id: 0023, name:'Ekans', type1:'Poison', type2:''},
      {id: 0024, name:'Arbok', type1:'Poison', type2:''},
      {id: 0025, name:'Pikachu', type1:'Electric', type2:''},
      {id: 0026, name:'Raichu', type1:'Electric', type2:''},
      {id: 0026, name:'Raichu-Alolan', type1:'Electric', type2:'Psychic'},
      {id: 0027, name:'Sandshrew', type1:'Ground', type2:''},
      {id: 0027, name:'Sandshrew-Alolan', type1:'Ice', type2:'Steel'},
      {id: 0028, name:'Sandslash', type1:'Ground', type2:''},
      {id: 0028, name:'Sandslash-Alolan', type1:'Ice', type2:'Steel'},
      {id: 0029, name:'Nidoran♀', type1:'Poison', type2:''},
      {id: 0030, name:'Nidorina', type1:'Poison', type2:''},
      {id: 0031, name:'Nidoqueen', type1:'Poison', type2:'Ground'},
      {id: 0032, name:'Nidoran♂', type1:'Poison', type2:''},
      {id: 0033, name:'Nidorino', type1:'Poison', type2:''},
      {id: 0034, name:'Nidoking', type1:'Poison', type2:'Ground'},
      {id: 0035, name:'CleFairy', type1:'Fairy', type2:''},
      {id: 0036, name:'Clefable', type1:'Fairy', type2:''},
      {id: 0037, name:'Vulpix', type1:'Fire', type2:''},
      {id: 0037, name:'Vulpix-Alolan', type1:'Ice', type2:''},
      {id: 0038, name:'Ninetales', type1:'Fire', type2:''},
      {id: 0038, name:'Ninetales-Alolan', type1:'Ice', type2:'Fairy'},
      {id: 0039, name:'Jigglypuff', type1:'Normal', type2:'Fairy'},
      {id: 0040, name:'Wigglytuff', type1:'Normal', type2:'Fairy'},
      {id: 0041, name:'Zubat', type1:'Poison', type2:'Flying'},
      {id: 0042, name:'Golbat', type1:'Poison', type2:'Flying'},
      {id: 0043, name:'Oddish', type1:'Grass', type2:'Poison'},
      {id: 0044, name:'Gloom', type1:'Grass', type2:'Poison'},
      {id: 0045, name:'Vileplume', type1:'Grass', type2:'Poison'},
      {id: 0046, name:'Paras', type1:'Bug', type2:'Grass'},
      {id: 0047, name:'Parasect', type1:'Bug', type2:'Grass'},
      {id: 0048, name:'Venonat', type1:'Bug', type2:'Poison'},
      {id: 0049, name:'Venomoth', type1:'Bug', type2:'Poison'},
      {id: 0050, name:'Diglett', type1:'Ground', type2:''},
      {id: 0050, name:'Diglett-Alolan', type1:'Ground', type2:'Steel'},
      {id: 0051, name:'Dugtrio', type1:'Ground', type2:''},
      {id: 0051, name:'Dugtrio-Alolan', type1:'Ground', type2:'Steel'},
      {id: 0052, name:'Meowth', type1:'Normal', type2:''},
      {id: 0052, name:'Meowth-Alolan', type1:'Dark', type2:''},
      {id: 0052, name:'Meowth-Galarian', type1:'Steel', type2:''},
      {id: 0053, name:'Persian', type1:'Normal', type2:''},
      {id: 0053, name:'Persian-Alolan', type1:'Dark', type2:''},
      {id: 0054, name:'Psyduck', type1:'Water', type2:''},
      {id: 0055, name:'Golduck', type1:'Water', type2:''},
      {id: 0056, name:'Mankey', type1:'Fighting', type2:''},
      {id: 0057, name:'Primeape', type1:'Fighting', type2:''},
      {id: 0058, name:'Growlithe', type1:'Fire', type2:''},
      {id: 0058, name:'Growlithe-Hisuian', type1:'Fire', type2:'Rock'},
      {id: 0059, name:'Arcanine', type1:'Fire', type2:''},
      {id: 0059, name:'Arcanine-Hisuian', type1:'Fire', type2:'Rock'},
      {id: 0060, name:'Poliwag', type1:'Water', type2:''},
      {id: 0061, name:'Poliwhirl', type1:'Water', type2:''},
      {id: 0062, name:'Poliwrath', type1:'Water', type2:'Fighting'},
      {id: 0063, name:'Abra', type1:'Psychic', type2:''},
      {id: 0064, name:'Kadabra', type1:'Psychic', type2:''},
      {id: 0065, name:'Alakazam', type1:'Psychic', type2:''},
      {id: 0065, name:'Alakazam-Mega', type1:'Psychic', type2:''},
      {id: 0066, name:'Machop', type1:'Fighting', type2:''},
      {id: 0067, name:'Machoke', type1:'Fighting', type2:''},
      {id: 0068, name:'Machamp', type1:'Fighting', type2:''},
      {id: 0069, name:'Bellsprout', type1:'Grass', type2:'Poison'},
      {id: 0070, name:'Weepinbell', type1:'Grass', type2:'Poison'},
      {id: 0071, name:'Victreebel', type1:'Grass', type2:'Poison'},
      {id: 0072, name:'Tentacool', type1:'Water', type2:'Poison'},
      {id: 0073, name:'Tentacruel', type1:'Water', type2:'Poison'},
      {id: 0074, name:'Geodude', type1:'Rock', type2:'Ground'},
      {id: 0074, name:'Geodude-Alolan', type1:'Rock', type2:'Electric'},
      {id: 0075, name:'Graveler', type1:'Rock', type2:'Ground'},
      {id: 0075, name:'Graveler-Alolan', type1:'Rock', type2:'Electric'},
      {id: 0076, name:'Golem', type1:'Rock', type2:'Ground'},
      {id: 0076, name:'Golem-Alolan', type1:'Rock', type2:'Electric'},
      {id: 0077, name:'Ponyta', type1:'Fire', type2:''},
      {id: 0077, name:'Ponyta-Galarian', type1:'Psychic', type2:''},
      {id: 0078, name:'Rapidash', type1:'Fire', type2:''},
      {id: 0078, name:'Rapidash-Galarian', type1:'Psychic', type2:'Fairy'},
      {id: 0079, name:'Slowpoke', type1:'Water', type2:'Psychic'},
      {id: 0079, name:'Slowpoke-Galarian', type1:'Psychic', type2:''},
      {id: 0080, name:'Slowbro', type1:'Water', type2:'Psychic'},
      {id: 0080, name:'Slowbro-Mega', type1:'Water', type2:'Psychic'},
      {id: 0080, name:'Slowbro-Galarian', type1:'Poison', type2:'Psychic'},
      {id: 0081, name:'Magnemite', type1:'Electric', type2:'Steel'},
      {id: 0082, name:'Magneton', type1:'Electric', type2:'Steel'},
      {id: 0083, name:'Farfetch\'d', type1:'Normal', type2:'Flying'},
      {id: 0083, name:'Farfetch\'d-Galarian', type1:'Fighting', type2:''},
      {id: 0084, name:'Doduo', type1:'Normal', type2:'Flying'},
      {id: 0085, name:'Dodrio', type1:'Normal', type2:'Flying'},
      {id: 0086, name:'Seel', type1:'Water', type2:''},
      {id: 0087, name:'Dewgong', type1:'Water', type2:'Ice'},
      {id: 0088, name:'Grimer', type1:'Poison', type2:''},
      {id: 0088, name:'Grimer-Alolan', type1:'Poison', type2:'Dark'},
      {id: 0089, name:'Muk', type1:'Poison', type2:''},
      {id: 0089, name:'Muk-Alolan', type1:'Poison', type2:'Dark'},
      {id: 0090, name:'Shellder', type1:'Water', type2:''},
      {id: 0091, name:'Cloyster', type1:'Water', type2:'Ice'},
      {id: 0092, name:'Gastly', type1:'Ghost', type2:'Poison'},
      {id: 0093, name:'Haunter', type1:'Ghost', type2:'Poison'},
      {id: 0094, name:'Gengar', type1:'Ghost', type2:'Poison'},
      {id: 0094, name:'Gengar-Mega', type1:'Ghost', type2:'Poison'},
      {id: 0095, name:'Onix', type1:'Rock', type2:'Ground'},
      {id: 0096, name:'Drowzee', type1:'Psychic', type2:''},
      {id: 0097, name:'Hypno', type1:'Psychic', type2:''},
      {id: 0098, name:'Krabby', type1:'Water', type2:''},
      {id: 0099, name:'Kingler', type1:'Water', type2:''},
      {id: 0100, name:'Voltorb', type1:'Electric', type2:''},
      {id: 0100, name:'Voltorb-Hisuian', type1:'Electric', type2:'Grass'},
      {id: 0101, name:'Electrode', type1:'Electric', type2:''},
      {id: 0101, name:'Electrode-Hisuian', type1:'Electric', type2:'Grass'},
      {id: 0102, name:'Exeggcute', type1:'Grass', type2:'Psychic'},
      {id: 0103, name:'Exeggutor', type1:'Grass', type2:'Psychic'},
      {id: 0103, name:'Exeggutor-Alolan', type1:'Grass', type2:'Dragon'},
      {id: 0104, name:'Cubone', type1:'Ground', type2:''},
      {id: 0105, name:'Marowak', type1:'Ground', type2:''},
      {id: 0105, name:'Marowak-Alolan', type1:'Fire', type2:'Ghost'},
      {id: 0106, name:'Hitmonlee', type1:'Fighting', type2:''},
      {id: 0107, name:'Hitmonchan', type1:'Fighting', type2:''},
      {id: 0108, name:'Lickitung', type1:'Normal', type2:''},
      {id: 0109, name:'Koffing', type1:'Poison', type2:''},
      {id: 0110, name:'Weezing', type1:'Poison', type2:''},
      {id: 0110, name:'Weezing-Galarian', type1:'Poison', type2:'Fairy'},
      {id: 0111, name:'Rhyhorn', type1:'Ground', type2:'Rock'},
      {id: 0112, name:'Rhydon', type1:'Ground', type2:'Rock'},
      {id: 0113, name:'Chansey', type1:'Normal', type2:''},
      {id: 0114, name:'Tangela', type1:'Grass', type2:''},
      {id: 0115, name:'Kangaskhan', type1:'Normal', type2:''},
      {id: 0115, name:'Kangaskhan-Mega', type1:'Normal', type2:''},
      {id: 0116, name:'Horsea', type1:'Water', type2:''},
      {id: 0117, name:'Seadra', type1:'Water', type2:''},
      {id: 0118, name:'Goldeen', type1:'Water', type2:''},
      {id: 0119, name:'Seaking', type1:'Water', type2:''},
      {id: 0120, name:'Staryu', type1:'Water', type2:''},
      {id: 0121, name:'Starmie', type1:'Water', type2:'Psychic'},
      {id: 0122, name:'Mr. Mime', type1:'Psychic', type2:'Fairy'},
      {id: 0122, name:'Mr. Mime-Galarian', type1:'Ice', type2:'Psychic'},
      {id: 0123, name:'Scyther', type1:'Bug', type2:'Flying'},
      {id: 0124, name:'Jynx', type1:'Ice', type2:'Psychic'},
      {id: 0125, name:'Electabuzz', type1:'Electric', type2:''},
      {id: 0126, name:'Magmar', type1:'Fire', type2:''},
      {id: 0127, name:'Pinsir', type1:'Bug', type2:''},
      {id: 0127, name:'Mega Pinsir', type1:'Bug', type2:'Flying'},
      {id: 0128, name:'Tauros', type1:'Normal', type2:''},
      {id: 0128, name:'Tauros-Paldean-Fighting', type1:'Fighting', type2:''},
      {id: 0128, name:'Tauros-Paldean-Fire', type1:'Fighting', type2:'Fire'},
      {id: 0128, name:'Tauros-Paldean-Water', type1:'Fighting', type2:'Water'},
      {id: 0129, name:'Magikarp', type1:'Water', type2:''},
      {id: 0130, name:'Gyarados', type1:'Water', type2:'Flying'},
      {id: 0130, name:'Gyarados-Mega', type1:'Water', type2:'Dark'},
      {id: 0131, name:'Lapras', type1:'Water', type2:'Ice'},
      {id: 0132, name:'Ditto', type1:'Normal', type2:''},
      {id: 0133, name:'Eevee', type1:'Normal', type2:''},
      {id: 0134, name:'Vaporeon', type1:'Water', type2:''},
      {id: 0135, name:'Jolteon', type1:'Electric', type2:''},
      {id: 0136, name:'Flareon', type1:'Fire', type2:''},
      {id: 0137, name:'Porygon', type1:'Normal', type2:''},
      {id: 0138, name:'Omanyte', type1:'Rock', type2:'Water'},
      {id: 0139, name:'Omastar', type1:'Rock', type2:'Water'},
      {id: 0140, name:'Kabuto', type1:'Rock', type2:'Water'},
      {id: 0141, name:'Kabutops', type1:'Rock', type2:'Water'},
      {id: 0142, name:'Aerodactyl', type1:'Rock', type2:'Flying'},
      {id: 0142, name:'Aerodactyl-Mega', type1:'Rock', type2:'Flying'},
      {id: 0143, name:'Snorlax', type1:'Normal', type2:''},
      {id: 0144, name:'Articuno', type1:'Ice', type2:'Flying'},
      {id: 0144, name:'Articuno-Galarian', type1:'Psychic', type2:'Flying'},
      {id: 0145, name:'Zapdos', type1:'Electric', type2:'Flying'},
      {id: 0145, name:'Zapdos-Galarian', type1:'Fighting', type2:'Flying'},
      {id: 0146, name:'Moltres', type1:'Fire', type2:'Flying'},
      {id: 0146, name:'Moltres-Galarian', type1:'Dark', type2:'Flying'},
      {id: 0147, name:'Dratini', type1:'Dragon', type2:''},
      {id: 0148, name:'Dragonair', type1:'Dragon', type2:''},
      {id: 0149, name:'Dragonite', type1:'Dragon', type2:'Flying'},
      {id: 0150, name:'Mewtwo', type1:'Psychic', type2:''},
      {id: 0150, name:'Mewtwo-Mega X', type1:'Psychic', type2:'Fighting'},
      {id: 0150, name:'Mewtwo-Mega Y', type1:'Psychic', type2:''},
      {id: 0151, name:'Mew', type1:'Psychic', type2:''},
      {id: 0152, name:'Chikorita', type1:'Grass', type2:''},
      {id: 0153, name:'Bayleef', type1:'Grass', type2:''},
      {id: 0154, name:'Meganium', type1:'Grass', type2:''},
      {id: 0155, name:'Cyndaquil', type1:'Fire', type2:''},
      {id: 0156, name:'Quilava', type1:'Fire', type2:''},
      {id: 0157, name:'Typhlosion', type1:'Fire', type2:''},
      {id: 0157, name:'Typhlosion-Hisuian', type1:'Fire', type2:'Ghost'},
      {id: 0158, name:'Totodile', type1:'Water', type2:''},
      {id: 0159, name:'Croconaw', type1:'Water', type2:''},
      {id: 0160, name:'Feraligatr', type1:'Water', type2:''},
      {id: 0161, name:'Sentret', type1:'Normal', type2:''},
      {id: 0162, name:'Furret', type1:'Normal', type2:''},
      {id: 0163, name:'Hoothoot', type1:'Normal', type2:'Flying'},
      {id: 0164, name:'Noctowl', type1:'Normal', type2:'Flying'},
      {id: 0165, name:'Ledyba', type1:'Bug', type2:'Flying'},
      {id: 0166, name:'Ledian', type1:'Bug', type2:'Flying'},
      {id: 0167, name:'Spinarak', type1:'Bug', type2:'Poison'},
      {id: 0168, name:'Ariados', type1:'Bug', type2:'Poison'},
      {id: 0169, name:'Crobat', type1:'Poison', type2:'Flying'},
      {id: 0170, name:'Chinchou', type1:'Water', type2:'Electric'},
      {id: 0171, name:'Lanturn', type1:'Water', type2:'Electric'},
      {id: 0172, name:'Pichu', type1:'Electric', type2:''},
      {id: 0173, name:'Cleffa', type1:'Fairy', type2:''},
      {id: 0174, name:'Igglybuff', type1:'Normal', type2:'Fairy'},
      {id: 0175, name:'Togepi', type1:'Fairy', type2:''},
      {id: 0176, name:'Togetic', type1:'Fairy', type2:'Flying'},
      {id: 0177, name:'Natu', type1:'Psychic', type2:'Flying'},
      {id: 0178, name:'Xatu', type1:'Psychic', type2:'Flying'},
      {id: 0179, name:'Mareep', type1:'Electric', type2:''},
      {id: 0180, name:'Flaaffy', type1:'Electric', type2:''},
      {id: 0181, name:'Ampharos', type1:'Electric', type2:''},
      {id: 0181, name:'Ampharos-Mega', type1:'Electric', type2:'Dragon'},
      {id: 0182, name:'Bellossom', type1:'Grass', type2:''},
      {id: 0183, name:'Marill', type1:'Water', type2:'Fairy'},
      {id: 0184, name:'Azumarill', type1:'Water', type2:'Fairy'},
      {id: 0185, name:'Sudowoodo', type1:'Rock', type2:''},
      {id: 0186, name:'Politoed', type1:'Water', type2:''},
      {id: 0187, name:'Hoppip', type1:'Grass', type2:'Flying'},
      {id: 0188, name:'Skiploom', type1:'Grass', type2:'Flying'},
      {id: 0189, name:'Jumpluff', type1:'Grass', type2:'Flying'},
      {id: 0190, name:'Aipom', type1:'Normal', type2:''},
      {id: 0191, name:'Sunkern', type1:'Grass', type2:''},
      {id: 0192, name:'Sunflora', type1:'Grass', type2:''},
      {id: 0193, name:'Yanma', type1:'Bug', type2:'Flying'},
      {id: 0194, name:'Wooper', type1:'Water', type2:'Ground'},
      {id: 0194, name:'Wooper-Paldea', type1:'Poison', type2:'Ground'},
      {id: 0195, name:'Quagsire', type1:'Water', type2:'Ground'},
      {id: 0196, name:'Espeon', type1:'Psychic', type2:''},
      {id: 0197, name:'Umbreon', type1:'Dark', type2:''},
      {id: 0198, name:'Murkrow', type1:'Dark', type2:'Flying'},
      {id: 0199, name:'Slowking', type1:'Water', type2:'Psychic'},
      {id: 0199, name:'Slowking-Galarian', type1:'Poison', type2:'Psychic'},
      {id: 0200, name:'Misdreavus', type1:'Ghost', type2:''},
      {id: 0201, name:'Unown', type1:'Psychic', type2:''},
      {id: 0202, name:'Wobbuffet', type1:'Psychic', type2:''},
      {id: 0203, name:'Girafarig', type1:'Normal', type2:'Psychic'},
      {id: 0204, name:'Pineco', type1:'Bug', type2:''},
      {id: 0205, name:'Forretress', type1:'Bug', type2:'Steel'},
      {id: 0206, name:'Dunsparce', type1:'Normal', type2:''},
      {id: 0207, name:'Gligar', type1:'Ground', type2:'Flying'},
      {id: 0208, name:'Steelix', type1:'Steel', type2:'Ground'},
      {id: 0208, name:'Steelix-Mega', type1:'Steel', type2:'Ground'},
      {id: 0209, name:'Snubbull', type1:'Fairy', type2:''},
      {id: 0210, name:'Granbull', type1:'Fairy', type2:''},
      {id: 0211, name:'Qwilfish', type1:'Water', type2:'Poison'},
      {id: 0211, name:'Qwilfish-Hisuian', type1:'Dark', type2:'Poison'},
      {id: 0212, name:'Scizor', type1:'Bug', type2:'Steel'},
      {id: 0212, name:'Scizor-Mega', type1:'Bug', type2:'Steel'},
      {id: 0213, name:'Shuckle', type1:'Bug', type2:'Rock'},
      {id: 0214, name:'Heracross', type1:'Bug', type2:'Fighting'},
      {id: 0214, name:'Heracross-Mega', type1:'Bug', type2:'Fighting'},
      {id: 0215, name:'Sneasel', type1:'Dark', type2:'Ice'},
      {id: 0215, name:'Sneasel-Hisuian', type1:'Poison', type2:'Fighting'},
      {id: 0216, name:'Teddiursa', type1:'Normal', type2:''},
      {id: 0217, name:'Ursaring', type1:'Normal', type2:''},
      {id: 0218, name:'Slugma', type1:'Fire', type2:''},
      {id: 0219, name:'Magcargo', type1:'Fire', type2:'Rock'},
      {id: 0220, name:'Swinub', type1:'Ice', type2:'Ground'},
      {id: 0221, name:'Piloswine', type1:'Ice', type2:'Ground'},
      {id: 0222, name:'Corsola', type1:'Water', type2:'Rock'},
      {id: 0222, name:'Corsola-Galarian', type1:'Ghost', type2:''},
      {id: 0223, name:'Remoraid', type1:'Water', type2:''},
      {id: 0224, name:'Octillery', type1:'Water', type2:''},
      {id: 0225, name:'Delibird', type1:'Ice', type2:'Flying'},
      {id: 0226, name:'Mantine', type1:'Water', type2:'Flying'},
      {id: 0227, name:'Skarmory', type1:'Steel', type2:'Flying'},
      {id: 0228, name:'Houndour', type1:'Dark', type2:'Fire'},
      {id: 0229, name:'Houndoom', type1:'Dark', type2:'Fire'},
      {id: 0229, name:'Houndoom-Mega', type1:'Dark', type2:'Fire'},
      {id: 0230, name:'Kingdra', type1:'Water', type2:'Dragon'},
      {id: 0231, name:'Phanpy', type1:'Ground', type2:''},
      {id: 0232, name:'Donphan', type1:'Ground', type2:''},
      {id: 0233, name:'Porygon2', type1:'Normal', type2:''},
      {id: 0234, name:'Stantler', type1:'Normal', type2:''},
      {id: 0235, name:'Smeargle', type1:'Normal', type2:''},
      {id: 0236, name:'Tyrogue', type1:'Fighting', type2:''},
      {id: 0237, name:'Hitmontop', type1:'Fighting', type2:''},
      {id: 0238, name:'Smoochum', type1:'Ice', type2:'Psychic'},
      {id: 0239, name:'Elekid', type1:'Electric', type2:''},
      {id: 0240, name:'Magby', type1:'Fire', type2:''},
      {id: 0241, name:'Miltank', type1:'Normal', type2:''},
      {id: 0242, name:'Blissey', type1:'Normal', type2:''},
      {id: 0243, name:'Raikou', type1:'Electric', type2:''},
      {id: 0244, name:'Entei', type1:'Fire', type2:''},
      {id: 0245, name:'Suicune', type1:'Water', type2:''},
      {id: 0246, name:'Larvitar', type1:'Rock', type2:'Ground'},
      {id: 0247, name:'Pupitar', type1:'Rock', type2:'Ground'},
      {id: 0248, name:'Tyranitar', type1:'Rock', type2:'Dark'},
      {id: 0248, name:'Tyranitar-Mega', type1:'Rock', type2:'Dark'},
      {id: 0249, name:'Lugia', type1:'Psychic', type2:'Flying'},
      {id: 0250, name:'Ho-oh', type1:'Fire', type2:'Flying'},
      {id: 0251, name:'Celebi', type1:'Psychic', type2:'Grass'},
      {id: 0252, name:'Treecko', type1:'Grass', type2:''},
      {id: 0253, name:'Grovyle', type1:'Grass', type2:''},
      {id: 0254, name:'Sceptile', type1:'Grass', type2:''},
      {id: 0254, name:'Sceptile-Mega', type1:'Grass', type2:'Dragon'},
      {id: 0255, name:'Torchic', type1:'Fire', type2:''},
      {id: 0256, name:'Combusken', type1:'Fire', type2:'Fighting'},
      {id: 0257, name:'Blaziken', type1:'Fire', type2:'Fighting'},
      {id: 0257, name:'Blaziken-Mega', type1:'Fire', type2:'Fighting'},
      {id: 0258, name:'Mudkip', type1:'Water', type2:''},
      {id: 0259, name:'Marshtomp', type1:'Water', type2:'Ground'},
      {id: 0260, name:'Swampert', type1:'Water', type2:'Ground'},
      {id: 0260, name:'Swampert-Mega', type1:'Water', type2:'Ground'},
      {id: 0261, name:'Poochyena', type1:'Dark', type2:''},
      {id: 0262, name:'Mightyena', type1:'Dark', type2:''},
      {id: 0263, name:'Zigzagoon', type1:'Normal', type2:''},
      {id: 0263, name:'Zigzagoon-Galarian', type1:'Dark', type2:'Normal'},
      {id: 0264, name:'Linoone', type1:'Normal', type2:''},
      {id: 0264, name:'Linoone-Galarian', type1:'Dark', type2:'Normal'},
      {id: 0265, name:'Wurmple', type1:'Bug', type2:''},
      {id: 0266, name:'Silcoon', type1:'Bug', type2:''},
      {id: 0267, name:'Beautifly', type1:'Bug', type2:'Flying'},
      {id: 0268, name:'Cascoon', type1:'Bug', type2:''},
      {id: 0269, name:'Dustox', type1:'Bug', type2:'Poison'},
      {id: 0270, name:'Lotad', type1:'Water', type2:'Grass'},
      {id: 0271, name:'Lombre', type1:'Water', type2:'Grass'},
      {id: 0272, name:'Ludicolo', type1:'Water', type2:'Grass'},
      {id: 0273, name:'Seedot', type1:'Grass', type2:''},
      {id: 0274, name:'Nuzleaf', type1:'Grass', type2:'Dark'},
      {id: 0275, name:'Shiftry', type1:'Grass', type2:'Dark'},
      {id: 0276, name:'Taillow', type1:'Normal', type2:'Flying'},
      {id: 0277, name:'Swellow', type1:'Normal', type2:'Flying'},
      {id: 0278, name:'Wingull', type1:'Water', type2:'Flying'},
      {id: 0279, name:'Pelipper', type1:'Water', type2:'Flying'},
      {id: 0280, name:'Ralts', type1:'Psychic', type2:'Fairy'},
      {id: 0281, name:'Kirlia', type1:'Psychic', type2:'Fairy'},
      {id: 0282, name:'Gardevoir', type1:'Psychic', type2:'Fairy'},
      {id: 0282, name:'Gardevoir-Mega', type1:'Psychic', type2:'Fairy'},
      {id: 0283, name:'Surskit', type1:'Bug', type2:'Water'},
      {id: 0284, name:'Masquerain', type1:'Bug', type2:'Flying'},
      {id: 0285, name:'Shroomish', type1:'Grass', type2:''},
      {id: 0286, name:'Breloom', type1:'Grass', type2:'Fighting'},
      {id: 0287, name:'Slakoth', type1:'Normal', type2:''},
      {id: 0288, name:'Vigoroth', type1:'Normal', type2:''},
      {id: 0289, name:'Slaking', type1:'Normal', type2:''},
      {id: 0290, name:'Nincada', type1:'Bug', type2:'Ground'},
      {id: 0291, name:'Ninjask', type1:'Bug', type2:'Flying'},
      {id: 0292, name:'Shedinja', type1:'Bug', type2:'Ghost'},
      {id: 0293, name:'Whismur', type1:'Normal', type2:''},
      {id: 0294, name:'Loudred', type1:'Normal', type2:''},
      {id: 0295, name:'Exploud', type1:'Normal', type2:''},
      {id: 0296, name:'Makuhita', type1:'Fighting', type2:''},
      {id: 0297, name:'Hariyama', type1:'Fighting', type2:''},
      {id: 0298, name:'Azurill', type1:'Normal', type2:'Fairy'},
      {id: 0299, name:'Nosepass', type1:'Rock', type2:''},
      {id: 0300, name:'Skitty', type1:'Normal', type2:''},
      {id: 0301, name:'Delcatty', type1:'Normal', type2:''},
      {id: 0302, name:'Sableye', type1:'Dark', type2:'Ghost'},
      {id: 0302, name:'Sableye-Mega', type1:'Dark', type2:'Ghost'},
      {id: 0303, name:'Mawile', type1:'Steel', type2:'Fairy'},
      {id: 0303, name:'Mawile-Mega', type1:'Steel', type2:'Fairy'},
      {id: 0304, name:'Aron', type1:'Steel', type2:'Rock'},
      {id: 0305, name:'Lairon', type1:'Steel', type2:'Rock'},
      {id: 0306, name:'Aggron', type1:'Steel', type2:'Rock'},
      {id: 0306, name:'Aggron-Mega', type1:'Steel', type2:''},
      {id: 0307, name:'Meditite', type1:'Fighting', type2:'Psychic'},
      {id: 0308, name:'Medicham', type1:'Fighting', type2:'Psychic'},
      {id: 0308, name:'Medicham-Mega', type1:'Fighting', type2:'Psychic'},
      {id: 0309, name:'Electrike', type1:'Electric', type2:''},
      {id: 0310, name:'Manectric', type1:'Electric', type2:''},
      {id: 0310, name:'Manectric-Mega', type1:'Electric', type2:''},
      {id: 0311, name:'Plusle', type1:'Electric', type2:''},
      {id: 0312, name:'Minun', type1:'Electric', type2:''},
      {id: 0313, name:'Volbeat', type1:'Bug', type2:''},
      {id: 0314, name:'Illumise', type1:'Bug', type2:''},
      {id: 0315, name:'Roselia', type1:'Grass', type2:'Poison'},
      {id: 0316, name:'Gulpin', type1:'Poison', type2:''},
      {id: 0317, name:'Swalot', type1:'Poison', type2:''},
      {id: 0318, name:'Carvanha', type1:'Water', type2:'Dark'},
      {id: 0319, name:'Sharpedo', type1:'Water', type2:'Dark'},
      {id: 0319, name:'Sharpedo-Mega', type1:'Water', type2:'Dark'},
      {id: 0320, name:'Wailmer', type1:'Water', type2:''},
      {id: 0321, name:'Wailord', type1:'Water', type2:''},
      {id: 0322, name:'Numel', type1:'Fire', type2:'Ground'},
      {id: 0323, name:'Camerupt', type1:'Fire', type2:'Ground'},
      {id: 0323, name:'Camerupt-Mega', type1:'Fire', type2:'Ground'},
      {id: 0324, name:'Torkoal', type1:'Fire', type2:''},
      {id: 0325, name:'Spoink', type1:'Psychic', type2:''},
      {id: 0326, name:'Grumpig', type1:'Psychic', type2:''},
      {id: 0327, name:'Spinda', type1:'Normal', type2:''},
      {id: 0328, name:'Trapinch', type1:'Ground', type2:''},
      {id: 0329, name:'Vibrava', type1:'Ground', type2:'Dragon'},
      {id: 0330, name:'Flygon', type1:'Ground', type2:'Dragon'},
      {id: 0331, name:'Cacnea', type1:'Grass', type2:''},
      {id: 0332, name:'Cacturne', type1:'Grass', type2:'Dark'},
      {id: 0333, name:'Swablu', type1:'Normal', type2:'Flying'},
      {id: 0334, name:'Altaria', type1:'Dragon', type2:'Flying'},
      {id: 0334, name:'Altaria-Mega', type1:'Dragon', type2:'Fairy'},
      {id: 0335, name:'Zangoose', type1:'Normal', type2:''},
      {id: 0336, name:'Seviper', type1:'Poison', type2:''},
      {id: 0337, name:'Lunatone', type1:'Rock', type2:'Psychic'},
      {id: 0338, name:'SolRock', type1:'Rock', type2:'Psychic'},
      {id: 0339, name:'Barboach', type1:'Water', type2:'Ground'},
      {id: 0340, name:'Whiscash', type1:'Water', type2:'Ground'},
      {id: 0341, name:'Corphish', type1:'Water', type2:''},
      {id: 0342, name:'Crawdaunt', type1:'Water', type2:'Dark'},
      {id: 0343, name:'Baltoy', type1:'Ground', type2:'Psychic'},
      {id: 0344, name:'Claydol', type1:'Ground', type2:'Psychic'},
      {id: 0345, name:'Lileep', type1:'Rock', type2:'Grass'},
      {id: 0346, name:'Cradily', type1:'Rock', type2:'Grass'},
      {id: 0347, name:'Anorith', type1:'Rock', type2:'Bug'},
      {id: 0348, name:'Armaldo', type1:'Rock', type2:'Bug'},
      {id: 0349, name:'Feebas', type1:'Water', type2:''},
      {id: 0350, name:'Milotic', type1:'Water', type2:''},
      {id: 0351, name:'Castform', type1:'Normal', type2:''},
      {id: 0351, name:'Castform-Sunny Form', type1:'Fire', type2:''},
      {id: 0351, name:'Castform-Rainy Form', type1:'Water', type2:''},
      {id: 0351, name:'Castform-Snowy Form', type1:'Ice', type2:''},
      {id: 0352, name:'Kecleon', type1:'Normal', type2:''},
      {id: 0353, name:'Shuppet', type1:'Ghost', type2:''},
      {id: 0354, name:'Banette', type1:'Ghost', type2:''},
      {id: 0354, name:'Banette-Mega', type1:'Ghost', type2:''},
      {id: 0355, name:'Duskull', type1:'Ghost', type2:''},
      {id: 0356, name:'Dusclops', type1:'Ghost', type2:''},
      {id: 0357, name:'Tropius', type1:'Grass', type2:'Flying'},
      {id: 0358, name:'Chimecho', type1:'Psychic', type2:''},
      {id: 0359, name:'Absol', type1:'Dark', type2:''},
      {id: 0359, name:'Absol-Mega', type1:'Dark', type2:''},
      {id: 0360, name:'Wynaut', type1:'Psychic', type2:''},
      {id: 0361, name:'Snorunt', type1:'Ice', type2:''},
      {id: 0362, name:'Glalie', type1:'Ice', type2:''},
      {id: 0362, name:'Glalie-Mega', type1:'Ice', type2:''},
      {id: 0363, name:'Spheal', type1:'Ice', type2:'Water'},
      {id: 0364, name:'Sealeo', type1:'Ice', type2:'Water'},
      {id: 0365, name:'Walrein', type1:'Ice', type2:'Water'},
      {id: 0366, name:'Clamperl', type1:'Water', type2:''},
      {id: 0367, name:'Huntail', type1:'Water', type2:''},
      {id: 0368, name:'Gorebyss', type1:'Water', type2:''},
      {id: 0369, name:'Relicanth', type1:'Water', type2:'Rock'},
      {id: 0370, name:'Luvdisc', type1:'Water', type2:''},
      {id: 0371, name:'Bagon', type1:'Dragon', type2:''},
      {id: 0372, name:'Shelgon', type1:'Dragon', type2:''},
      {id: 0373, name:'Salamence', type1:'Dragon', type2:'Flying'},
      {id: 0373, name:'Salamence-Mega', type1:'Dragon', type2:'Flying'},
      {id: 0374, name:'Beldum', type1:'Steel', type2:'Psychic'},
      {id: 0375, name:'Metang', type1:'Steel', type2:'Psychic'},
      {id: 0376, name:'Metagross', type1:'Steel', type2:'Psychic'},
      {id: 0376, name:'Metagross-Mega', type1:'Steel', type2:'Psychic'},
      {id: 0377, name:'RegiRock', type1:'Rock', type2:''},
      {id: 0378, name:'RegIce', type1:'Ice', type2:''},
      {id: 0379, name:'RegiSteel', type1:'Steel', type2:''},
      {id: 0380, name:'Latias', type1:'Dragon', type2:'Psychic'},
      {id: 0380, name:'Latias-Mega', type1:'Dragon', type2:'Psychic'},
      {id: 0381, name:'Latios', type1:'Dragon', type2:'Psychic'},
      {id: 0381, name:'Latios-Mega', type1:'Dragon', type2:'Psychic'},
      {id: 0382, name:'Kyogre', type1:'Water', type2:''},
      {id: 0382, name:'Kyogre-Primal', type1:'Water', type2:''},
      {id: 0383, name:'Groudon', type1:'Ground', type2:''},
      {id: 0383, name:'Groudon-Primal', type1:'Ground', type2:'Fire'},
      {id: 0384, name:'Rayquaza', type1:'Dragon', type2:'Flying'},
      {id: 0384, name:'Rayquaza-Mega', type1:'Dragon', type2:'Flying'},
      {id: 0385, name:'Jirachi', type1:'Steel', type2:'Psychic'},
      {id: 0386, name:'Deoxys-Normal Form', type1:'Psychic', type2:''},
      {id: 0386, name:'Deoxys-Attack Form', type1:'Psychic', type2:''},
      {id: 0386, name:'Deoxys-Defense Form', type1:'Psychic', type2:''},
      {id: 0386, name:'Deoxys-Speed Form', type1:'Psychic', type2:''},
      {id: 0387, name:'Turtwig', type1:'Grass', type2:''},
      {id: 0388, name:'Grotle', type1:'Grass', type2:''},
      {id: 0389, name:'Torterra', type1:'Grass', type2:'Ground'},
      {id: 0390, name:'Chimchar', type1:'Fire', type2:''},
      {id: 0391, name:'Monferno', type1:'Fire', type2:'Fighting'},
      {id: 0392, name:'Infernape', type1:'Fire', type2:'Fighting'},
      {id: 0393, name:'Piplup', type1:'Water', type2:''},
      {id: 0394, name:'Prinplup', type1:'Water', type2:''},
      {id: 0395, name:'Empoleon', type1:'Water', type2:'Steel'},
      {id: 0396, name:'Starly', type1:'Normal', type2:'Flying'},
      {id: 0397, name:'Staravia', type1:'Normal', type2:'Flying'},
      {id: 0398, name:'Staraptor', type1:'Normal', type2:'Flying'},
      {id: 0399, name:'Bidoof', type1:'Normal', type2:''},
      {id: 0400, name:'Bibarel', type1:'Normal', type2:'Water'},
      {id: 0401, name:'Kricketot', type1:'Bug', type2:''},
      {id: 0402, name:'Kricketune', type1:'Bug', type2:''},
      {id: 0403, name:'Shinx', type1:'Electric', type2:''},
      {id: 0404, name:'Luxio', type1:'Electric', type2:''},
      {id: 0405, name:'Luxray', type1:'Electric', type2:''},
      {id: 0406, name:'Budew', type1:'Grass', type2:'Poison'},
      {id: 0407, name:'Roserade', type1:'Grass', type2:'Poison'},
      {id: 0408, name:'Cranidos', type1:'Rock', type2:''},
      {id: 0409, name:'Rampardos', type1:'Rock', type2:''},
      {id: 0410, name:'Shieldon', type1:'Rock', type2:'Steel'},
      {id: 0411, name:'Bastiodon', type1:'Rock', type2:'Steel'},
      {id: 0412, name:'Burmy-Plant Cloak', type1:'Bug', type2:''},
      {id: 0412, name:'Burmy-Sandy Cloak', type1:'Bug', type2:''},
      {id: 0412, name:'Burmy-Trash Cloak', type1:'Bug', type2:''},
      {id: 0413, name:'Wormadam-Plant Cloak', type1:'Bug', type2:'Grass'},
      {id: 0413, name:'Wormadam-Sandy Cloak', type1:'Bug', type2:'Ground'},
      {id: 0413, name:'Wormadam-Trash Cloak', type1:'Bug', type2:'Steel'},
      {id: 0414, name:'Mothim', type1:'Bug', type2:'Flying'},
      {id: 0415, name:'Combee', type1:'Bug', type2:'Flying'},
      {id: 0416, name:'Vespiquen', type1:'Bug', type2:'Flying'},
      {id: 0417, name:'Pachirisu', type1:'Electric', type2:''},
      {id: 0418, name:'Buizel', type1:'Water', type2:''},
      {id: 0419, name:'Floatzel', type1:'Water', type2:''},
      {id: 0420, name:'Cherubi', type1:'Grass', type2:''},
      {id: 0421, name:'Cherrim', type1:'Grass', type2:''},
      {id: 0422, name:'Shellos', type1:'Water', type2:''},
      {id: 0423, name:'Gastrodon', type1:'Water', type2:'Ground'},
      {id: 0424, name:'Ambipom', type1:'Normal', type2:''},
      {id: 0425, name:'Drifloon', type1:'Ghost', type2:'Flying'},
      {id: 0426, name:'Drifblim', type1:'Ghost', type2:'Flying'},
      {id: 0427, name:'Buneary', type1:'Normal', type2:''},
      {id: 0428, name:'Lopunny', type1:'Normal', type2:''},
      {id: 0428, name:'Lopunny-Mega', type1:'Normal', type2:'Fighting'},
      {id: 0429, name:'Mismagius', type1:'Ghost', type2:''},
      {id: 0430, name:'Honchkrow', type1:'Dark', type2:'Flying'},
      {id: 0431, name:'Glameow', type1:'Normal', type2:''},
      {id: 0432, name:'Purugly', type1:'Normal', type2:''},
      {id: 0433, name:'Chingling', type1:'Psychic', type2:''},
      {id: 0434, name:'Stunky', type1:'Poison', type2:'Dark'},
      {id: 0435, name:'Skuntank', type1:'Poison', type2:'Dark'},
      {id: 0436, name:'Bronzor', type1:'Steel', type2:'Psychic'},
      {id: 0437, name:'Bronzong', type1:'Steel', type2:'Psychic'},
      {id: 0438, name:'Bonsly', type1:'Rock', type2:''},
      {id: 0439, name:'Mime Jr.', type1:'Psychic', type2:'Fairy'},
      {id: 0440, name:'Happiny', type1:'Normal', type2:''},
      {id: 0441, name:'Chatot', type1:'Normal', type2:'Flying'},
      {id: 0442, name:'Spiritomb', type1:'Ghost', type2:'Dark'},
      {id: 0443, name:'Gible', type1:'Dragon', type2:'Ground'},
      {id: 0444, name:'Gabite', type1:'Dragon', type2:'Ground'},
      {id: 0445, name:'Garchomp', type1:'Dragon', type2:'Ground'},
      {id: 0445, name:'Garchomp-Mega', type1:'Dragon', type2:'Ground'},
      {id: 0446, name:'Munchlax', type1:'Normal', type2:''},
      {id: 0447, name:'Riolu', type1:'Fighting', type2:''},
      {id: 0448, name:'Lucario', type1:'Fighting', type2:'Steel'},
      {id: 0448, name:'Lucario-Mega', type1:'Fighting', type2:'Steel'},
      {id: 0449, name:'Hippopotas', type1:'Ground', type2:''},
      {id: 0450, name:'Hippowdon', type1:'Ground', type2:''},
      {id: 0451, name:'Skorupi', type1:'Poison', type2:'Bug'},
      {id: 0452, name:'Drapion', type1:'Poison', type2:'Dark'},
      {id: 0453, name:'Croagunk', type1:'Poison', type2:'Fighting'},
      {id: 0454, name:'Toxicroak', type1:'Poison', type2:'Fighting'},
      {id: 0455, name:'Carnivine', type1:'Grass', type2:''},
      {id: 0456, name:'Finneon', type1:'Water', type2:''},
      {id: 0457, name:'Lumineon', type1:'Water', type2:''},
      {id: 0458, name:'Mantyke', type1:'Water', type2:'Flying'},
      {id: 0459, name:'Snover', type1:'Grass', type2:'Ice'},
      {id: 0460, name:'Abomasnow', type1:'Grass', type2:'Ice'},
      {id: 0460, name:'Abomasnow-Mega', type1:'Grass', type2:'Ice'},
      {id: 0461, name:'Weavile', type1:'Dark', type2:'Ice'},
      {id: 0462, name:'Magnezone', type1:'Electric', type2:'Steel'},
      {id: 0463, name:'Lickilicky', type1:'Normal', type2:''},
      {id: 0464, name:'Rhyperior', type1:'Ground', type2:'Rock'},
      {id: 0465, name:'Tangrowth', type1:'Grass', type2:''},
      {id: 0466, name:'Electivire', type1:'Electric', type2:''},
      {id: 0467, name:'Magmortar', type1:'Fire', type2:''},
      {id: 0468, name:'Togekiss', type1:'Fairy', type2:'Flying'},
      {id: 0469, name:'Yanmega', type1:'Bug', type2:'Flying'},
      {id: 0470, name:'Leafeon', type1:'Grass', type2:''},
      {id: 0471, name:'Glaceon', type1:'Ice', type2:''},
      {id: 0472, name:'Gliscor', type1:'Ground', type2:'Flying'},
      {id: 0473, name:'Mamoswine', type1:'Ice', type2:'Ground'},
      {id: 0474, name:'Porygon-Z', type1:'Normal', type2:''},
      {id: 0475, name:'Gallade', type1:'Psychic', type2:'Fighting'},
      {id: 0475, name:'Gallade-Mega', type1:'Psychic', type2:'Fighting'},
      {id: 0476, name:'Probopass', type1:'Rock', type2:'Steel'},
      {id: 0477, name:'Dusknoir', type1:'Ghost', type2:''},
      {id: 0478, name:'Froslass', type1:'Ice', type2:'Ghost'},
      {id: 0479, name:'Rotom', type1:'Electric', type2:'Ghost'},
      {id: 0479, name:'Rotom-Heat', type1:'Electric', type2:'Fire'},
      {id: 0479, name:'Rotom-Wash', type1:'Electric', type2:'Water'},
      {id: 0479, name:'Rotom-Frost', type1:'Electric', type2:'Ice'},
      {id: 0479, name:'Rotom-Fan', type1:'Electric', type2:'Flying'},
      {id: 0479, name:'Rotom-Mow', type1:'Electric', type2:'Grass'},
      {id: 0480, name:'Uxie', type1:'Psychic', type2:''},
      {id: 0481, name:'Mesprit', type1:'Psychic', type2:''},
      {id: 0482, name:'Azelf', type1:'Psychic', type2:''},
      {id: 0483, name:'Dialga', type1:'Steel', type2:'Dragon'},
      {id: 0483, name:'Dialga-Origin Form', type1:'Steel', type2:'Dragon'},
      {id: 0484, name:'Palkia', type1:'Water', type2:'Dragon'},
      {id: 0484, name:'Palkia-Origin Form', type1:'Water', type2:'Dragon'},
      {id: 0485, name:'Heatran', type1:'Fire', type2:'Steel'},
      {id: 0486, name:'Regigigas', type1:'Normal', type2:''},
      {id: 0487, name:'Giratina-Altered Form', type1:'Ghost', type2:'Dragon'},
      {id: 0487, name:'Giratina-Origin Form', type1:'Ghost', type2:'Dragon'},
      {id: 0488, name:'Cresselia', type1:'Psychic', type2:''},
      {id: 0489, name:'Phione', type1:'Water', type2:''},
      {id: 0490, name:'Manaphy', type1:'Water', type2:''},
      {id: 0491, name:'Darkrai', type1:'Dark', type2:''},
      {id: 0492, name:'Shaymin-Land Form', type1:'Grass', type2:''},
      {id: 0492, name:'Shaymin-Sky Form', type1:'Grass', type2:'Flying'},
      {id: 0493, name:'Arceus', type1:'Normal', type2:''},
      {id: 0494, name:'Victini', type1:'Psychic', type2:'Fire'},
      {id: 0495, name:'Snivy', type1:'Grass', type2:''},
      {id: 0496, name:'Servine', type1:'Grass', type2:''},
      {id: 0497, name:'Serperior', type1:'Grass', type2:''},
      {id: 0498, name:'Tepig', type1:'Fire', type2:''},
      {id: 0499, name:'Pignite', type1:'Fire', type2:'Fighting'},
      {id: 0500, name:'Emboar', type1:'Fire', type2:'Fighting'},
      {id: 0501, name:'Oshawott', type1:'Water', type2:''},
      {id: 0502, name:'Dewott', type1:'Water', type2:''},
      {id: 0503, name:'Samurott', type1:'Water', type2:''},
      {id: 0503, name:'Samurott-Hisuian', type1:'Water', type2:'Dark'},
      {id: 0504, name:'Patrat', type1:'Normal', type2:''},
      {id: 0505, name:'Watchog', type1:'Normal', type2:''},
      {id: 0506, name:'Lillipup', type1:'Normal', type2:''},
      {id: 0507, name:'Herdier', type1:'Normal', type2:''},
      {id: 0508, name:'Stoutland', type1:'Normal', type2:''},
      {id: 0509, name:'Purrloin', type1:'Dark', type2:''},
      {id: 0510, name:'Liepard', type1:'Dark', type2:''},
      {id: 0511, name:'Pansage', type1:'Grass', type2:''},
      {id: 0512, name:'Simisage', type1:'Grass', type2:''},
      {id: 0513, name:'Pansear', type1:'Fire', type2:''},
      {id: 0514, name:'Simisear', type1:'Fire', type2:''},
      {id: 0515, name:'Panpour', type1:'Water', type2:''},
      {id: 0516, name:'Simipour', type1:'Water', type2:''},
      {id: 0517, name:'Munna', type1:'Psychic', type2:''},
      {id: 0518, name:'Musharna', type1:'Psychic', type2:''},
      {id: 0519, name:'Pidove', type1:'Normal', type2:'Flying'},
      {id: 0520, name:'Tranquill', type1:'Normal', type2:'Flying'},
      {id: 0521, name:'Unfezant', type1:'Normal', type2:'Flying'},
      {id: 0522, name:'Blitzle', type1:'Electric', type2:''},
      {id: 0523, name:'Zebstrika', type1:'Electric', type2:''},
      {id: 0524, name:'Roggenrola', type1:'Rock', type2:''},
      {id: 0525, name:'Boldore', type1:'Rock', type2:''},
      {id: 0526, name:'Gigalith', type1:'Rock', type2:''},
      {id: 0527, name:'Woobat', type1:'Psychic', type2:'Flying'},
      {id: 0528, name:'Swoobat', type1:'Psychic', type2:'Flying'},
      {id: 0529, name:'Drilbur', type1:'Ground', type2:''},
      {id: 0530, name:'Excadrill', type1:'Ground', type2:'Steel'},
      {id: 0531, name:'Audino', type1:'Normal', type2:''},
      {id: 0531, name:'Audino-Mega', type1:'Normal', type2:'Fairy'},
      {id: 0532, name:'Timburr', type1:'Fighting', type2:''},
      {id: 0533, name:'Gurdurr', type1:'Fighting', type2:''},
      {id: 0534, name:'Conkeldurr', type1:'Fighting', type2:''},
      {id: 0535, name:'Tympole', type1:'Water', type2:''},
      {id: 0536, name:'Palpitoad', type1:'Water', type2:'Ground'},
      {id: 0537, name:'Seismitoad', type1:'Water', type2:'Ground'},
      {id: 0538, name:'Throh', type1:'Fighting', type2:''},
      {id: 0539, name:'Sawk', type1:'Fighting', type2:''},
      {id: 0540, name:'Sewaddle', type1:'Bug', type2:'Grass'},
      {id: 0541, name:'Swadloon', type1:'Bug', type2:'Grass'},
      {id: 0542, name:'Leavanny', type1:'Bug', type2:'Grass'},
      {id: 0543, name:'Venipede', type1:'Bug', type2:'Poison'},
      {id: 0544, name:'Whirlipede', type1:'Bug', type2:'Poison'},
      {id: 0545, name:'Scolipede', type1:'Bug', type2:'Poison'},
      {id: 0546, name:'Cottonee', type1:'Grass', type2:'Fairy'},
      {id: 0547, name:'Whimsicott', type1:'Grass', type2:'Fairy'},
      {id: 0548, name:'Petilil', type1:'Grass', type2:''},
      {id: 0549, name:'Lilligant', type1:'Grass', type2:''},
      {id: 0549, name:'Lilligant-Hisuian', type1:'Grass', type2:'Fighting'},
      {id: 0550, name:'Basculin-Red-Striped Form', type1:'Water', type2:''},
      {id: 0550, name:'Basculin-Blue-Striped Form', type1:'Water', type2:''},
      {id: 0550, name:'Basculin-White-Striped Form', type1:'Water', type2:''},
      {id: 0551, name:'Sandile', type1:'Ground', type2:'Dark'},
      {id: 0552, name:'Krokorok', type1:'Ground', type2:'Dark'},
      {id: 0553, name:'Krookodile', type1:'Ground', type2:'Dark'},
      {id: 0554, name:'Darumaka', type1:'Fire', type2:''},
      {id: 0554, name:'Darumaka-Galarian', type1:'Ice', type2:''},
      {id: 0555, name:'Darmanitan-Standard Mode', type1:'Fire', type2:''},
      {id: 0555, name:'Darmanitan-Zen Mode', type1:'Fire', type2:'Psychic'},
      {id: 0555, name:'Darmanitan-Galarian Standard Mode', type1:'Ice', type2:''},
      {id: 0555, name:'Darmanitan-Galarian Zen Mode', type1:'Ice', type2:'Fire'},
      {id: 0556, name:'Maractus', type1:'Grass', type2:''},
      {id: 0557, name:'Dwebble', type1:'Bug', type2:'Rock'},
      {id: 0558, name:'Crustle', type1:'Bug', type2:'Rock'},
      {id: 0559, name:'Scraggy', type1:'Dark', type2:'Fighting'},
      {id: 0560, name:'Scrafty', type1:'Dark', type2:'Fighting'},
      {id: 0561, name:'Sigilyph', type1:'Psychic', type2:'Flying'},
      {id: 0562, name:'Yamask', type1:'Ghost', type2:''},
      {id: 0562, name:'Yamask-Galarian', type1:'Ground', type2:'Ghost'},
      {id: 0563, name:'Cofagrigus', type1:'Ghost', type2:''},
      {id: 0564, name:'Tirtouga', type1:'Water', type2:'Rock'},
      {id: 0565, name:'Carracosta', type1:'Water', type2:'Rock'},
      {id: 0566, name:'Archen', type1:'Rock', type2:'Flying'},
      {id: 0567, name:'Archeops', type1:'Rock', type2:'Flying'},
      {id: 0568, name:'Trubbish', type1:'Poison', type2:''},
      {id: 0569, name:'Garbodor', type1:'Poison', type2:''},
      {id: 0570, name:'Zorua', type1:'Dark', type2:''},
      {id: 0570, name:'Zorua-Hisuian', type1:'Normal', type2:'Ghost'},
      {id: 0571, name:'Zoroark', type1:'Dark', type2:''},
      {id: 0571, name:'Zoroark-Hisuian', type1:'Normal', type2:'Ghost'},
      {id: 0572, name:'Minccino', type1:'Normal', type2:''},
      {id: 0573, name:'Cinccino', type1:'Normal', type2:''},
      {id: 0574, name:'Gothita', type1:'Psychic', type2:''},
      {id: 0575, name:'Gothorita', type1:'Psychic', type2:''},
      {id: 0576, name:'Gothitelle', type1:'Psychic', type2:''},
      {id: 0577, name:'Solosis', type1:'Psychic', type2:''},
      {id: 0578, name:'Duosion', type1:'Psychic', type2:''},
      {id: 0579, name:'Reuniclus', type1:'Psychic', type2:''},
      {id: 0580, name:'Ducklett', type1:'Water', type2:'Flying'},
      {id: 0581, name:'Swanna', type1:'Water', type2:'Flying'},
      {id: 0582, name:'Vanillite', type1:'Ice', type2:''},
      {id: 0583, name:'Vanillish', type1:'Ice', type2:''},
      {id: 0584, name:'Vanilluxe', type1:'Ice', type2:''},
      {id: 0585, name:'Deerling', type1:'Normal', type2:'Grass'},
      {id: 0586, name:'Sawsbuck', type1:'Normal', type2:'Grass'},
      {id: 0587, name:'Emolga', type1:'Electric', type2:'Flying'},
      {id: 0588, name:'Karrablast', type1:'Bug', type2:''},
      {id: 0589, name:'Escavalier', type1:'Bug', type2:'Steel'},
      {id: 0590, name:'Foongus', type1:'Grass', type2:'Poison'},
      {id: 0591, name:'Amoonguss', type1:'Grass', type2:'Poison'},
      {id: 0592, name:'Frillish', type1:'Water', type2:'Ghost'},
      {id: 0593, name:'JellIcent', type1:'Water', type2:'Ghost'},
      {id: 0594, name:'Alomomola', type1:'Water', type2:''},
      {id: 0595, name:'Joltik', type1:'Bug', type2:'Electric'},
      {id: 0596, name:'Galvantula', type1:'Bug', type2:'Electric'},
      {id: 0597, name:'Ferroseed', type1:'Grass', type2:'Steel'},
      {id: 0598, name:'Ferrothorn', type1:'Grass', type2:'Steel'},
      {id: 0599, name:'Klink', type1:'Steel', type2:''},
      {id: 0600, name:'Klang', type1:'Steel', type2:''},
      {id: 0601, name:'Klinklang', type1:'Steel', type2:''},
      {id: 0602, name:'Tynamo', type1:'Electric', type2:''},
      {id: 0603, name:'Eelektrik', type1:'Electric', type2:''},
      {id: 0604, name:'Eelektross', type1:'Electric', type2:''},
      {id: 0605, name:'Elgyem', type1:'Psychic', type2:''},
      {id: 0606, name:'Beheeyem', type1:'Psychic', type2:''},
      {id: 0607, name:'Litwick', type1:'Ghost', type2:'Fire'},
      {id: 0608, name:'Lampent', type1:'Ghost', type2:'Fire'},
      {id: 0609, name:'Chandelure', type1:'Ghost', type2:'Fire'},
      {id: 0610, name:'Axew', type1:'Dragon', type2:''},
      {id: 0611, name:'Fraxure', type1:'Dragon', type2:''},
      {id: 0612, name:'Haxorus', type1:'Dragon', type2:''},
      {id: 0613, name:'Cubchoo', type1:'Ice', type2:''},
      {id: 0614, name:'Beartic', type1:'Ice', type2:''},
      {id: 0615, name:'Cryogonal', type1:'Ice', type2:''},
      {id: 0616, name:'Shelmet', type1:'Bug', type2:''},
      {id: 0617, name:'Accelgor', type1:'Bug', type2:''},
      {id: 0618, name:'Stunfisk', type1:'Ground', type2:'Electric'},
      {id: 0618, name:'Stunfisk-Galarian', type1:'Ground', type2:'Steel'},
      {id: 0619, name:'Mienfoo', type1:'Fighting', type2:''},
      {id: 0620, name:'Mienshao', type1:'Fighting', type2:''},
      {id: 0621, name:'Druddigon', type1:'Dragon', type2:''},
      {id: 0622, name:'Golett', type1:'Ground', type2:'Ghost'},
      {id: 0623, name:'Golurk', type1:'Ground', type2:'Ghost'},
      {id: 0624, name:'Pawniard', type1:'Dark', type2:'Steel'},
      {id: 0625, name:'Bisharp', type1:'Dark', type2:'Steel'},
      {id: 0626, name:'Bouffalant', type1:'Normal', type2:''},
      {id: 0627, name:'Rufflet', type1:'Normal', type2:'Flying'},
      {id: 0628, name:'Braviary', type1:'Normal', type2:'Flying'},
      {id: 0628, name:'Braviary-Hisuian', type1:'Psychic', type2:'Flying'},
      {id: 0629, name:'Vullaby', type1:'Dark', type2:'Flying'},
      {id: 0630, name:'Mandibuzz', type1:'Dark', type2:'Flying'},
      {id: 0631, name:'Heatmor', type1:'Fire', type2:''},
      {id: 0632, name:'Durant', type1:'Bug', type2:'Steel'},
      {id: 0633, name:'Deino', type1:'Dark', type2:'Dragon'},
      {id: 0634, name:'Zweilous', type1:'Dark', type2:'Dragon'},
      {id: 0635, name:'Hydreigon', type1:'Dark', type2:'Dragon'},
      {id: 0636, name:'Larvesta', type1:'Bug', type2:'Fire'},
      {id: 0637, name:'Volcarona', type1:'Bug', type2:'Fire'},
      {id: 0638, name:'Cobalion', type1:'Steel', type2:'Fighting'},
      {id: 0639, name:'Terrakion', type1:'Rock', type2:'Fighting'},
      {id: 0640, name:'Virizion', type1:'Grass', type2:'Fighting'},
      {id: 0641, name:'Tornadus-Incarnate Forme', type1:'Flying', type2:''},
      {id: 0641, name:'Tornadus-Therian Forme', type1:'Flying', type2:''},
      {id: 0642, name:'Thundurus-Incarnate Forme', type1:'Electric', type2:'Flying'},
      {id: 0642, name:'Thundurus-Therian Forme', type1:'Electric', type2:'Flying'},
      {id: 0643, name:'Reshiram', type1:'Dragon', type2:'Fire'},
      {id: 0644, name:'Zekrom', type1:'Dragon', type2:'Electric'},
      {id: 0645, name:'Landorus-Incarnate Forme', type1:'Ground', type2:'Flying'},
      {id: 0645, name:'Landorus-Therian Forme', type1:'Ground', type2:'Flying'},
      {id: 0646, name:'Kyurem', type1:'Dragon', type2:'Ice'},
      {id: 0646, name:'Kyurem-White', type1:'Dragon', type2:'Ice'},
      {id: 0646, name:'Kyurem-Black', type1:'Dragon', type2:'Ice'},
      {id: 0647, name:'Keldeo-Ordinary Form', type1:'Water', type2:'Fighting'},
      {id: 0647, name:'Keldeo-Resolute Form', type1:'Water', type2:'Fighting'},
      {id: 0648, name:'Meloetta-Aria Forme', type1:'Normal', type2:'Psychic'},
      {id: 0648, name:'Meloetta-Pirouette Forme', type1:'Normal', type2:'Fighting'},
      {id: 0649, name:'Genesect', type1:'Bug', type2:'Steel'},
      {id: 0650, name:'Chespin', type1:'Grass', type2:''},
      {id: 0651, name:'Quilladin', type1:'Grass', type2:''},
      {id: 0652, name:'Chesnaught', type1:'Grass', type2:'Fighting'},
      {id: 0653, name:'Fennekin', type1:'Fire', type2:''},
      {id: 0654, name:'Braixen', type1:'Fire', type2:''},
      {id: 0655, name:'Delphox', type1:'Fire', type2:'Psychic'},
      {id: 0656, name:'Froakie', type1:'Water', type2:''},
      {id: 0657, name:'Frogadier', type1:'Water', type2:''},
      {id: 0658, name:'Greninja', type1:'Water', type2:'Dark'},
      {id: 0658, name:'Greninja-Ash', type1:'Water', type2:'Dark'},
      {id: 0659, name:'Bunnelby', type1:'Normal', type2:''},
      {id: 0660, name:'Diggersby', type1:'Normal', type2:'Ground'},
      {id: 0661, name:'Fletchling', type1:'Normal', type2:'Flying'},
      {id: 0662, name:'Fletchinder', type1:'Fire', type2:'Flying'},
      {id: 0663, name:'Talonflame', type1:'Fire', type2:'Flying'},
      {id: 0664, name:'ScatterBug', type1:'Bug', type2:''},
      {id: 0665, name:'Spewpa', type1:'Bug', type2:''},
      {id: 0666, name:'Vivillon', type1:'Bug', type2:'Flying'},
      {id: 0667, name:'Litleo', type1:'Fire', type2:'Normal'},
      {id: 0668, name:'Pyroar', type1:'Fire', type2:'Normal'},
      {id: 0669, name:'Flabébé', type1:'Fairy', type2:''},
      {id: 0670, name:'Floette', type1:'Fairy', type2:''},
      {id: 0671, name:'Florges', type1:'Fairy', type2:''},
      {id: 0672, name:'Skiddo', type1:'Grass', type2:''},
      {id: 0673, name:'Gogoat', type1:'Grass', type2:''},
      {id: 0674, name:'Pancham', type1:'Fighting', type2:''},
      {id: 0675, name:'Pangoro', type1:'Fighting', type2:'Dark'},
      {id: 0676, name:'Furfrou', type1:'Normal', type2:''},
      {id: 0677, name:'Espurr', type1:'Psychic', type2:''},
      {id: 0678, name:'Meowstic-Male', type1:'Psychic', type2:''},
      {id: 0678, name:'Meowstic-Female', type1:'Psychic', type2:''},
      {id: 0679, name:'Honedge', type1:'Steel', type2:'Ghost'},
      {id: 0680, name:'Doublade', type1:'Steel', type2:'Ghost'},
      {id: 0681, name:'Aegislash-Shield Forme', type1:'Steel', type2:'Ghost'},
      {id: 0681, name:'Aegislash-Blade Forme', type1:'Steel', type2:'Ghost'},
      {id: 0682, name:'Spritzee', type1:'Fairy', type2:''},
      {id: 0683, name:'Aromatisse', type1:'Fairy', type2:''},
      {id: 0684, name:'Swirlix', type1:'Fairy', type2:''},
      {id: 0685, name:'Slurpuff', type1:'Fairy', type2:''},
      {id: 0686, name:'Inkay', type1:'Dark', type2:'Psychic'},
      {id: 0687, name:'Malamar', type1:'Dark', type2:'Psychic'},
      {id: 0688, name:'Binacle', type1:'Rock', type2:'Water'},
      {id: 0689, name:'Barbaracle', type1:'Rock', type2:'Water'},
      {id: 0690, name:'Skrelp', type1:'Poison', type2:'Water'},
      {id: 0691, name:'Dragalge', type1:'Poison', type2:'Dragon'},
      {id: 0692, name:'Clauncher', type1:'Water', type2:''},
      {id: 0693, name:'Clawitzer', type1:'Water', type2:''},
      {id: 0694, name:'Helioptile', type1:'Electric', type2:'Normal'},
      {id: 0695, name:'Heliolisk', type1:'Electric', type2:'Normal'},
      {id: 0696, name:'Tyrunt', type1:'Rock', type2:'Dragon'},
      {id: 0697, name:'Tyrantrum', type1:'Rock', type2:'Dragon'},
      {id: 0698, name:'Amaura', type1:'Rock', type2:'Ice'},
      {id: 0699, name:'Aurorus', type1:'Rock', type2:'Ice'},
      {id: 0700, name:'Sylveon', type1:'Fairy', type2:''},
      {id: 0701, name:'Hawlucha', type1:'Fighting', type2:'Flying'},
      {id: 0702, name:'Dedenne', type1:'Electric', type2:'Fairy'},
      {id: 0703, name:'Carbink', type1:'Rock', type2:'Fairy'},
      {id: 0704, name:'Goomy', type1:'Dragon', type2:''},
      {id: 0705, name:'Sliggoo', type1:'Dragon', type2:''},
      {id: 0705, name:'Sliggoo-Hisuian', type1:'Steel', type2:'Dragon'},
      {id: 0706, name:'Goodra', type1:'Dragon', type2:''},
      {id: 0706, name:'Goodra-Hisuian', type1:'Steel', type2:'Dragon'},
      {id: 0707, name:'Klefki', type1:'Steel', type2:'Fairy'},
      {id: 0708, name:'Phantump', type1:'Ghost', type2:'Grass'},
      {id: 0709, name:'Trevenant', type1:'Ghost', type2:'Grass'},
      {id: 0710, name:'Pumpkaboo-Average Size', type1:'Ghost', type2:'Grass'},
      {id: 0710, name:'Pumpkaboo-Small Size', type1:'Ghost', type2:'Grass'},
      {id: 0710, name:'Pumpkaboo-Large Size', type1:'Ghost', type2:'Grass'},
      {id: 0710, name:'Pumpkaboo-Super Size', type1:'Ghost', type2:'Grass'},
      {id: 0711, name:'Gourgeist-Average Size', type1:'Ghost', type2:'Grass'},
      {id: 0711, name:'Gourgeist-Small Size', type1:'Ghost', type2:'Grass'},
      {id: 0711, name:'Gourgeist-Large Size', type1:'Ghost', type2:'Grass'},
      {id: 0711, name:'Gourgeist-Super Size', type1:'Ghost', type2:'Grass'},
      {id: 0712, name:'Bergmite', type1:'Ice', type2:''},
      {id: 0713, name:'Avalugg', type1:'Ice', type2:''},
      {id: 0713, name:'Avalugg-Hisuian', type1:'Ice', type2:'Rock'},
      {id: 0714, name:'Noibat', type1:'Flying', type2:'Dragon'},
      {id: 0715, name:'Noivern', type1:'Flying', type2:'Dragon'},
      {id: 0716, name:'Xerneas', type1:'Fairy', type2:''},
      {id: 0717, name:'Yveltal', type1:'Dark', type2:'Flying'},
      {id: 0718, name:'Zygarde-50% Forme', type1:'Dragon', type2:'Ground'},
      {id: 0718, name:'Zygarde-10% Forme', type1:'Dragon', type2:'Ground'},
      {id: 0718, name:'Zygarde-Complete Forme', type1:'Dragon', type2:'Ground'},
      {id: 0719, name:'Diancie', type1:'Rock', type2:'Fairy'},
      {id: 0719, name:'Diancie-Mega', type1:'Rock', type2:'Fairy'},
      {id: 0720, name:'Hoopa-Confined', type1:'Psychic', type2:'Ghost'},
      {id: 0720, name:'Hoopa-Unbound', type1:'Psychic', type2:'Dark'},
      {id: 0721, name:'Volcanion', type1:'Fire', type2:'Water'},
      {id: 0722, name:'Rowlet', type1:'Grass', type2:'Flying'},
      {id: 0723, name:'Dartrix', type1:'Grass', type2:'Flying'},
      {id: 0724, name:'Decidueye', type1:'Grass', type2:'Ghost'},
      {id: 0724, name:'Decidueye-Hisuian', type1:'Grass', type2:'Fighting'},
      {id: 0725, name:'Litten', type1:'Fire', type2:''},
      {id: 0726, name:'Torracat', type1:'Fire', type2:''},
      {id: 0727, name:'Incineroar', type1:'Fire', type2:'Dark'},
      {id: 0728, name:'Popplio', type1:'Water', type2:''},
      {id: 0729, name:'Brionne', type1:'Water', type2:''},
      {id: 0730, name:'Primarina', type1:'Water', type2:'Fairy'},
      {id: 0731, name:'Pikipek', type1:'Normal', type2:'Flying'},
      {id: 0732, name:'Trumbeak', type1:'Normal', type2:'Flying'},
      {id: 0733, name:'Toucannon', type1:'Normal', type2:'Flying'},
      {id: 0734, name:'Yungoos', type1:'Normal', type2:''},
      {id: 0735, name:'Gumshoos', type1:'Normal', type2:''},
      {id: 0736, name:'Grubbin', type1:'Bug', type2:''},
      {id: 0737, name:'CharjaBug', type1:'Bug', type2:'Electric'},
      {id: 0738, name:'Vikavolt', type1:'Bug', type2:'Electric'},
      {id: 0739, name:'Crabrawler', type1:'Fighting', type2:''},
      {id: 0740, name:'Crabominable', type1:'Fighting', type2:'Ice'},
      {id: 0741, name:'Oricorio-Baile Style', type1:'Fire', type2:'Flying'},
      {id: 0741, name:'Oricorio-Pom-Pom Style', type1:'Electric', type2:'Flying'},
      {id: 0741, name:'Oricorio-Pa\'u Style', type1:'Psychic', type2:'Flying'},
      {id: 0741, name:'Oricorio-Sensu Style', type1:'Ghost', type2:'Flying'},
      {id: 0742, name:'Cutiefly', type1:'Bug', type2:'Fairy'},
      {id: 0743, name:'Ribombee', type1:'Bug', type2:'Fairy'},
      {id: 0744, name:'Rockruff', type1:'Rock', type2:''},
      {id: 0745, name:'Lycanroc-Midday Form', type1:'Rock', type2:''},
      {id: 0745, name:'Lycanroc-Midnight Form', type1:'Rock', type2:''},
      {id: 0745, name:'Lycanroc-Dusk Form', type1:'Rock', type2:''},
      {id: 0746, name:'Wishiwashi-Solo Form', type1:'Water', type2:''},
      {id: 0746, name:'Wishiwashi-School Form', type1:'Water', type2:''},
      {id: 0747, name:'Mareanie', type1:'Poison', type2:'Water'},
      {id: 0748, name:'Toxapex', type1:'Poison', type2:'Water'},
      {id: 0749, name:'Mudbray', type1:'Ground', type2:''},
      {id: 0750, name:'Mudsdale', type1:'Ground', type2:''},
      {id: 0751, name:'Dewpider', type1:'Water', type2:'Bug'},
      {id: 0752, name:'Araquanid', type1:'Water', type2:'Bug'},
      {id: 0753, name:'Fomantis', type1:'Grass', type2:''},
      {id: 0754, name:'Lurantis', type1:'Grass', type2:''},
      {id: 0755, name:'Morelull', type1:'Grass', type2:'Fairy'},
      {id: 0756, name:'Shiinotic', type1:'Grass', type2:'Fairy'},
      {id: 0757, name:'Salandit', type1:'Poison', type2:'Fire'},
      {id: 0758, name:'Salazzle', type1:'Poison', type2:'Fire'},
      {id: 0759, name:'Stufful', type1:'Normal', type2:'Fighting'},
      {id: 0760, name:'Bewear', type1:'Normal', type2:'Fighting'},
      {id: 0761, name:'Bounsweet', type1:'Grass', type2:''},
      {id: 0762, name:'Steenee', type1:'Grass', type2:''},
      {id: 0763, name:'Tsareena', type1:'Grass', type2:''},
      {id: 0764, name:'Comfey', type1:'Fairy', type2:''},
      {id: 0765, name:'Oranguru', type1:'Normal', type2:'Psychic'},
      {id: 0766, name:'Passimian', type1:'Fighting', type2:''},
      {id: 0767, name:'Wimpod', type1:'Bug', type2:'Water'},
      {id: 0768, name:'Golisopod', type1:'Bug', type2:'Water'},
      {id: 0769, name:'Sandygast', type1:'Ghost', type2:'Ground'},
      {id: 0770, name:'Palossand', type1:'Ghost', type2:'Ground'},
      {id: 0771, name:'Pyukumuku', type1:'Water', type2:''},
      {id: 0772, name:'Type: Null', type1:'Normal', type2:''},
      {id: 0773, name:'Silvally', type1:'Normal', type2:''},
      {id: 0774, name:'Minior-Meteor Form', type1:'Rock', type2:'Flying'},
      {id: 0774, name:'Minior-Core Form', type1:'Rock', type2:'Flying'},
      {id: 0775, name:'Komala', type1:'Normal', type2:''},
      {id: 0776, name:'Turtonator', type1:'Fire', type2:'Dragon'},
      {id: 0777, name:'Togedemaru', type1:'Electric', type2:'Steel'},
      {id: 0778, name:'Mimikyu', type1:'Ghost', type2:'Fairy'},
      {id: 0779, name:'Bruxish', type1:'Water', type2:'Psychic'},
      {id: 0780, name:'Drampa', type1:'Normal', type2:'Dragon'},
      {id: 0781, name:'Dhelmise', type1:'Ghost', type2:'Grass'},
      {id: 0782, name:'Jangmo-o', type1:'Dragon', type2:''},
      {id: 0783, name:'Hakamo-o', type1:'Dragon', type2:'Fighting'},
      {id: 0784, name:'Kommo-o', type1:'Dragon', type2:'Fighting'},
      {id: 0785, name:'Tapu Koko', type1:'Electric', type2:'Fairy'},
      {id: 0786, name:'Tapu Lele', type1:'Psychic', type2:'Fairy'},
      {id: 0787, name:'Tapu Bulu', type1:'Grass', type2:'Fairy'},
      {id: 0788, name:'Tapu Fini', type1:'Water', type2:'Fairy'},
      {id: 0789, name:'Cosmog', type1:'Psychic', type2:''},
      {id: 0790, name:'Cosmoem', type1:'Psychic', type2:''},
      {id: 0791, name:'Solgaleo', type1:'Psychic', type2:'Steel'},
      {id: 0792, name:'Lunala', type1:'Psychic', type2:'Ghost'},
      {id: 0793, name:'Nihilego', type1:'Rock', type2:'Poison'},
      {id: 0794, name:'Buzzwole', type1:'Bug', type2:'Fighting'},
      {id: 0795, name:'Pheromosa', type1:'Bug', type2:'Fighting'},
      {id: 0796, name:'Xurkitree', type1:'Electric', type2:''},
      {id: 0797, name:'CeleSteela', type1:'Steel', type2:'Flying'},
      {id: 0798, name:'Kartana', type1:'Grass', type2:'Steel'},
      {id: 0799, name:'Guzzlord', type1:'Dark', type2:'Dragon'},
      {id: 0800, name:'Necrozma', type1:'Psychic', type2:''},
      {id: 0800, name:'Necrozma-Dusk Mane', type1:'Psychic', type2:'Steel'},
      {id: 0800, name:'Necrozma-Dawn Wings', type1:'Psychic', type2:'Ghost'},
      {id: 0800, name:'Necrozma-Ultra', type1:'Psychic', type2:'Dragon'},
      {id: 0801, name:'Magearna', type1:'Steel', type2:'Fairy'},
      {id: 0802, name:'Marshadow', type1:'Fighting', type2:'Ghost'},
      {id: 0803, name:'Poipole', type1:'Poison', type2:''},
      {id: 0804, name:'Naganadel', type1:'Poison', type2:'Dragon'},
      {id: 0805, name:'Stakataka', type1:'Rock', type2:'Steel'},
      {id: 0806, name:'Blacephalon', type1:'Fire', type2:'Ghost'},
      {id: 0807, name:'Zeraora', type1:'Electric', type2:''},
      {id: 0808, name:'Meltan', type1:'Steel', type2:''},
      {id: 0809, name:'Melmetal', type1:'Steel', type2:''},
      {id: 0810, name:'Grookey', type1:'Grass', type2:''},
      {id: 0811, name:'Thwackey', type1:'Grass', type2:''},
      {id: 0812, name:'Rillaboom', type1:'Grass', type2:''},
      {id: 0813, name:'Scorbunny', type1:'Fire', type2:''},
      {id: 0814, name:'Raboot', type1:'Fire', type2:''},
      {id: 0815, name:'Cinderace', type1:'Fire', type2:''},
      {id: 0816, name:'Sobble', type1:'Water', type2:''},
      {id: 0817, name:'Drizzile', type1:'Water', type2:''},
      {id: 0818, name:'Inteleon', type1:'Water', type2:''},
      {id: 0819, name:'Skwovet', type1:'Normal', type2:''},
      {id: 0820, name:'Greedent', type1:'Normal', type2:''},
      {id: 0821, name:'Rookidee', type1:'Flying', type2:''},
      {id: 0822, name:'Corvisquire', type1:'Flying', type2:''},
      {id: 0823, name:'Corviknight', type1:'Flying', type2:'Steel'},
      {id: 0824, name:'BlipBug', type1:'Bug', type2:''},
      {id: 0825, name:'Dottler', type1:'Bug', type2:'Psychic'},
      {id: 0826, name:'Orbeetle', type1:'Bug', type2:'Psychic'},
      {id: 0827, name:'Nickit', type1:'Dark', type2:''},
      {id: 0828, name:'Thievul', type1:'Dark', type2:''},
      {id: 0829, name:'Gossifleur', type1:'Grass', type2:''},
      {id: 0830, name:'Eldegoss', type1:'Grass', type2:''},
      {id: 0831, name:'Wooloo', type1:'Normal', type2:''},
      {id: 0832, name:'Dubwool', type1:'Normal', type2:''},
      {id: 0833, name:'Chewtle', type1:'Water', type2:''},
      {id: 0834, name:'Drednaw', type1:'Water', type2:'Rock'},
      {id: 0835, name:'Yamper', type1:'Electric', type2:''},
      {id: 0836, name:'Boltund', type1:'Electric', type2:''},
      {id: 0837, name:'Rolycoly', type1:'Rock', type2:''},
      {id: 0838, name:'Carkol', type1:'Rock', type2:'Fire'},
      {id: 0839, name:'Coalossal', type1:'Rock', type2:'Fire'},
      {id: 0840, name:'Applin', type1:'Grass', type2:'Dragon'},
      {id: 0841, name:'Flapple', type1:'Grass', type2:'Dragon'},
      {id: 0842, name:'Appletun', type1:'Grass', type2:'Dragon'},
      {id: 0843, name:'Silicobra', type1:'Ground', type2:''},
      {id: 0844, name:'Sandaconda', type1:'Ground', type2:''},
      {id: 0845, name:'Cramorant', type1:'Flying', type2:'Water'},
      {id: 0846, name:'Arrokuda', type1:'Water', type2:''},
      {id: 0847, name:'Barraskewda', type1:'Water', type2:''},
      {id: 0848, name:'Toxel', type1:'Electric', type2:'Poison'},
      {id: 0849, name:'Toxtricity-Amped Form', type1:'Electric', type2:'Poison'},
      {id: 0849, name:'Toxtricity-Low Key Form', type1:'Electric', type2:'Poison'},
      {id: 0850, name:'Sizzlipede', type1:'Fire', type2:'Bug'},
      {id: 0851, name:'Centiskorch', type1:'Fire', type2:'Bug'},
      {id: 0852, name:'Clobbopus', type1:'Fighting', type2:''},
      {id: 0853, name:'Grapploct', type1:'Fighting', type2:''},
      {id: 0854, name:'Sinistea', type1:'Ghost', type2:''},
      {id: 0855, name:'Polteageist', type1:'Ghost', type2:''},
      {id: 0856, name:'Hatenna', type1:'Psychic', type2:''},
      {id: 0857, name:'Hattrem', type1:'Psychic', type2:''},
      {id: 0858, name:'Hatterene', type1:'Psychic', type2:'Fairy'},
      {id: 0859, name:'Impidimp', type1:'Dark', type2:'Fairy'},
      {id: 0860, name:'Morgrem', type1:'Dark', type2:'Fairy'},
      {id: 0861, name:'Grimmsnarl', type1:'Dark', type2:'Fairy'},
      {id: 0862, name:'Obstagoon', type1:'Dark', type2:'Normal'},
      {id: 0863, name:'Perrserker', type1:'Steel', type2:''},
      {id: 0864, name:'Cursola', type1:'Ghost', type2:''},
      {id: 0865, name:'Sirfetch\'d', type1:'Fighting', type2:''},
      {id: 0866, name:'Mr. Rime', type1:'Ice', type2:'Psychic'},
      {id: 0867, name:'Runerigus', type1:'Ground', type2:'Ghost'},
      {id: 0868, name:'Milcery', type1:'Fairy', type2:''},
      {id: 0869, name:'Alcremie', type1:'Fairy', type2:''},
      {id: 0870, name:'Falinks', type1:'Fighting', type2:''},
      {id: 0871, name:'Pincurchin', type1:'Electric', type2:''},
      {id: 0872, name:'Snom', type1:'Ice', type2:'Bug'},
      {id: 0873, name:'Frosmoth', type1:'Ice', type2:'Bug'},
      {id: 0874, name:'Stonjourner', type1:'Rock', type2:''},
      {id: 0875, name:'Eiscue-Ice Face', type1:'Ice', type2:''},
      {id: 0875, name:'Eiscue-No-Ice Face', type1:'Ice', type2:''},
      {id: 0876, name:'Indeedee-Male', type1:'Psychic', type2:'Normal'},
      {id: 0876, name:'Indeedee-Female', type1:'Psychic', type2:'Normal'},
      {id: 0877, name:'Morpeko-Full Belly Mode', type1:'Electric', type2:'Dark'},
      {id: 0877, name:'Morpeko-Hangry Mode', type1:'Electric', type2:'Dark'},
      {id: 0878, name:'Cufant', type1:'Steel', type2:''},
      {id: 0879, name:'Copperajah', type1:'Steel', type2:''},
      {id: 0880, name:'Dracozolt', type1:'Electric', type2:'Dragon'},
      {id: 0881, name:'Arctozolt', type1:'Electric', type2:'Ice'},
      {id: 0882, name:'Dracovish', type1:'Water', type2:'Dragon'},
      {id: 0883, name:'Arctovish', type1:'Water', type2:'Ice'},
      {id: 0884, name:'Duraludon', type1:'Steel', type2:'Dragon'},
      {id: 0885, name:'Dreepy', type1:'Dragon', type2:'Ghost'},
      {id: 0886, name:'Drakloak', type1:'Dragon', type2:'Ghost'},
      {id: 0887, name:'Dragapult', type1:'Dragon', type2:'Ghost'},
      {id: 0888, name:'Zacian-Hero of Many Battles', type1:'Fairy', type2:''},
      {id: 0888, name:'Zacian-Crowned Sword', type1:'Fairy', type2:'Steel'},
      {id: 0889, name:'Zamazenta-Hero of Many Battles', type1:'Fighting', type2:''},
      {id: 0889, name:'Zamazenta-Crowned Shield', type1:'Fighting', type2:'Steel'},
      {id: 0890, name:'Eternatus', type1:'Poison', type2:'Dragon'},
      {id: 0890, name:'Eternatus-Eternamax', type1:'Poison', type2:'Dragon'},
      {id: 0891, name:'Kubfu', type1:'Fighting', type2:''},
      {id: 0892, name:'Urshifu-Single Strike Style', type1:'Fighting', type2:'Dark'},
      {id: 0892, name:'Urshifu-Rapid Strike Style', type1:'Fighting', type2:'Water'},
      {id: 0893, name:'Zarude', type1:'Dark', type2:'Grass'},
      {id: 0894, name:'Regieleki', type1:'Electric', type2:''},
      {id: 0895, name:'Regidrago', type1:'Dragon', type2:''},
      {id: 0896, name:'Glastrier', type1:'Ice', type2:''},
      {id: 0897, name:'Spectrier', type1:'Ghost', type2:''},
      {id: 0898, name:'Calyrex', type1:'Psychic', type2:'Grass'},
      {id: 0898, name:'Calyrex-Ice Rider', type1:'Psychic', type2:'Ice'},
      {id: 0898, name:'Calyrex-Shadow Rider', type1:'Psychic', type2:'Ghost'},
      {id: 0899, name:'Wyrdeer', type1:'Normal', type2:'Psychic'},
      {id: 0900, name:'Kleavor', type1:'Bug', type2:'Rock'},
      {id: 0901, name:'Ursaluna', type1:'Ground', type2:'Normal'},
      {id: 0902, name:'Basculegion-Male', type1:'Water', type2:'Ghost'},
      {id: 0902, name:'Basculegion-Female', type1:'Water', type2:'Ghost'},
      {id: 0903, name:'Sneasler', type1:'Poison', type2:'Fighting'},
      {id: 0904, name:'Overqwil', type1:'Dark', type2:'Poison'},
      {id: 0905, name:'Enamorus-Incarnate Forme', type1:'Fairy', type2:'Flying'},
      {id: 0905, name:'Enamorus-Therian Forme', type1:'Fairy', type2:'Flying'},
      {id: 0906, name:'Sprigatito', type1:'Grass', type2:''},
      {id: 0907, name:'Floragato', type1:'Grass', type2:''},
      {id: 0908, name:'Meowscarada', type1:'Grass', type2:'Dark'},
      {id: 0909, name:'Fuecoco', type1:'Fire', type2:''},
      {id: 0910, name:'Crocalor', type1:'Fire', type2:''},
      {id: 0911, name:'Skeledirge', type1:'Fire', type2:'Ghost'},
      {id: 0912, name:'Quaxly', type1:'Water', type2:''},
      {id: 0913, name:'Quaxwell', type1:'Water', type2:''},
      {id: 0914, name:'Quaquaval', type1:'Water', type2:'Fighting'},
      {id: 0915, name:'Lechonk', type1:'Normal', type2:''},
      {id: 0916, name:'Oinkologne-Male', type1:'Normal', type2:''},
      {id: 0916, name:'Oinkologne-Female', type1:'Normal', type2:''},
      {id: 0917, name:'Dudunsparce', type1:'Normal', type2:''},
      {id: 0918, name:'Tarountula', type1:'Bug', type2:''},
      {id: 0919, name:'Spidops', type1:'Bug', type2:''},
      {id: 0920, name:'Nymble', type1:'Bug', type2:''},
      {id: 0921, name:'Lokix', type1:'Bug', type2:'Dark'},
      {id: 0922, name:'Rellor', type1:'Bug', type2:''},
      {id: 0923, name:'Rabsca', type1:'Bug', type2:'Psychic'},
      {id: 0924, name:'Greavard', type1:'Ghost', type2:''},
      {id: 0925, name:'Houndstone', type1:'Ghost', type2:''},
      {id: 0926, name:'Flittle', type1:'Psychic', type2:''},
      {id: 0927, name:'Espathra', type1:'Psychic', type2:''},
      {id: 0928, name:'Farigiraf', type1:'Normal', type2:'Psychic'},
      {id: 0929, name:'Wiglett', type1:'Water', type2:''},
      {id: 0930, name:'Wugtrio', type1:'Water', type2:''},
      {id: 0931, name:'Dondozo', type1:'Water', type2:''},
      {id: 0932, name:'Veluza', type1:'Water', type2:''},
      {id: 0933, name:'Finizen', type1:'Water', type2:''},
      {id: 0934, name:'Palafin', type1:'Water', type2:''},
      {id: 0934, name:'Palafin-Hero', type1:'Water', type2:''},
      {id: 0935, name:'Smoliv', type1:'Grass', type2:'Normal'},
      {id: 0936, name:'Dolliv', type1:'Grass', type2:'Normal'},
      {id: 0937, name:'Arboliva', type1:'Grass', type2:'Normal'},
      {id: 0938, name:'Capsakid', type1:'Grass', type2:'Fire'},
      {id: 0939, name:'Scovillain', type1:'Grass', type2:'Fire'},
      {id: 0940, name:'Tadbulb', type1:'Electric', type2:''},
      {id: 0941, name:'Bellibolt', type1:'Electric', type2:''},
      {id: 0942, name:'Varoom', type1:'Poison', type2:'Steel'},
      {id: 0943, name:'Revavroom', type1:'Poison', type2:'Steel'},
      {id: 0944, name:'Orthworm', type1:'Steel', type2:''},
      {id: 0945, name:'Tandemaus', type1:'Normal', type2:''},
      {id: 0946, name:'Maushold', type1:'Normal', type2:''},
      {id: 0947, name:'Cetoddle', type1:'Ice', type2:''},
      {id: 0948, name:'Cetitan', type1:'Ice', type2:''},
      {id: 0949, name:'Frigibax', type1:'Dragon', type2:'Ice'},
      {id: 0950, name:'Arctibax', type1:'Dragon', type2:'Ice'},
      {id: 0951, name:'Baxcalibur', type1:'Dragon', type2:'Ice'},
      {id: 0952, name:'Tatsugiri', type1:'Dragon', type2:'Water'},
      {id: 0953, name:'Cyclizar', type1:'Dragon', type2:'Normal'},
      {id: 0954, name:'Pawmi', type1:'Electric', type2:''},
      {id: 0955, name:'Pawmo', type1:'Electric', type2:'Fighting'},
      {id: 0956, name:'Pawmot', type1:'Electric', type2:'Fighting'},
      {id: 0957, name:'Wattrel', type1:'Flying', type2:'Electric'},
      {id: 0958, name:'Kilowattrel', type1:'Flying', type2:'Electric'},
      {id: 0959, name:'Bombirdier', type1:'Flying', type2:'Dark'},
      {id: 0960, name:'Squawkabilly-Blue', type1:'Normal', type2:'Flying'},
      {id: 0960, name:'Squawkabilly-Green', type1:'Normal', type2:'Flying'},
      {id: 0960, name:'Squawkabilly-Yellow', type1:'Normal', type2:'Flying'},
      {id: 0961, name:'Flamigo', type1:'Flying', type2:'Fighting'},
      {id: 0962, name:'Flawf', type1:'Rock', type2:''},
      {id: 0963, name:'Nacli', type1:'Rock', type2:''},
      {id: 0964, name:'Naclstack', type1:'Rock', type2:''},
      {id: 0965, name:'Garganacl', type1:'Rock', type2:''},
      {id: 0966, name:'Glimmet', type1:'Poison', type2:'Rock'},
      {id: 0967, name:'Glimmora', type1:'Poison', type2:'Rock'},
      {id: 0968, name:'Shroodle', type1:'Poison', type2:'Normal'},
      {id: 0969, name:'Grafaiai', type1:'Poison', type2:'Normal'},
      {id: 0970, name:'Fidough', type1:'Fairy', type2:''},
      {id: 0971, name:'Dachsbun', type1:'Fairy', type2:''},
      {id: 0972, name:'Maschiff', type1:'Dark', type2:''},
      {id: 0973, name:'Mabosstiff', type1:'Dark', type2:''},
      {id: 0974, name:'Bramblin', type1:'Grass', type2:'Ghost'},
      {id: 0975, name:'Brambleghast', type1:'Grass', type2:'Ghost'},
      {id: 0976, name:'Gimmighoul-Chest Form', type1:'Ghost', type2:''},
      {id: 0976, name:'Gimmighoul-Roaming Form', type1:'Ghost', type2:''},
      {id: 0977, name:'Gholdengo', type1:'Ghost', type2:'Steel'},
      {id: 0978, name:'Great Tusk', type1:'Ground', type2:'Fighting'},
      {id: 0979, name:'Brute Bonnet', type1:'Grass', type2:'Dark'},
      {id: 0980, name:'??? (Suicune)', type1:'', type2:''},
      {id: 0981, name:'Sandy Shocks', type1:'Electric', type2:'Ground'},
      {id: 0982, name:'Scream Tail', type1:'Fairy', type2:'Psychic'},
      {id: 0983, name:'Flutter Mane', type1:'Ghost', type2:'Fairy'},
      {id: 0984, name:'Slither Wing', type1:'Bug', type2:'Fighting'},
      {id: 0985, name:'Roaring Moon', type1:'Dragon', type2:'Dark'},
      {id: 0986, name:'Iron Treads', type1:'Ground', type2:'Steel'},
      {id: 0987, name:'??? (Virizion)', type1:'', type2:''},
      {id: 0988, name:'Iron Moth', type1:'Fire', type2:'Poison'},
      {id: 0989, name:'Iron Hands', type1:'Fighting', type2:'Electric'},
      {id: 0990, name:'Iron Jugulis', type1:'Dark', type2:'Flying'},
      {id: 0991, name:'Iron Thorns', type1:'Rock', type2:'Electric'},
      {id: 0992, name:'Iron Bundle', type1:'Ice', type2:'Water'},
      {id: 0993, name:'Iron Valiant', type1:'Fighting', type2:'Fairy'},
      {id: 0994, name:'Ting-Lu', type1:'Dark', type2:'Ground'},
      {id: 0995, name:'Chien-Pao', type1:'Dark', type2:'Ice'},
      {id: 0996, name:'Wo-Chien', type1:'Dark', type2:'Grass'},
      {id: 0997, name:'Chi-Yu', type1:'Dark', type2:'Fire'},
      {id: 0998, name:'Koraidon', type1:'Fighting', type2:'Dragon'},
      {id: 0999, name:'Miraidon', type1:'Electric', type2:'Dragon'},
      {id: 1000, name:'Tinkatink', type1:'Fairy', type2:'Steel'},
      {id: 1001, name:'Tinkatuff', type1:'Fairy', type2:'Steel'},
      {id: 1002, name:'Tinkaton', type1:'Fairy', type2:'Steel'},
      {id: 1003, name:'Charcadet', type1:'Fire', type2:''},
      {id: 1004, name:'Armarouge', type1:'Fire', type2:'Psychic'},
      {id: 1005, name:'Ceruledge', type1:'Fire', type2:'Ghost'},
      {id: 1006, name:'Toedscool', type1:'Grass', type2:'Ground'},
      {id: 1007, name:'Toedscruel', type1:'Grass', type2:'Ground'},
      {id: 1008, name:'Kingambit', type1:'Dark', type2:'Steel'},
      {id: 1009, name:'Clodsire', type1:'Poison', type2:'Ground'},
      {id: 1010, name:'Annihilape', type1:'Fighting', type2:'Ghost'},
    ];
    chart = {
      'Normal': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 0.5,
        'Bug': 1,
        'Ghost': 0,
        'Steel': 0.5,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 1
      },
      'Fighting': {
        'Normal': 2,
        'Fighting': 1,
        'Flying': 0.5,
        'Poison': 0.5,
        'Ground': 1,
        'Rock': 2,
        'Bug': 0.5,
        'Ghost': 0,
        'Steel': 2,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 0.5,
        'Ice': 2,
        'Dragon': 1,
        'Dark': 2,
        'Fairy': 0.5
      },
      'Flying': {
        'Normal': 1,
        'Fighting': 2,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 0.5,
        'Bug': 2,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 1,
        'Water': 1,
        'Grass': 2,
        'Electric': 0.5,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 1
      },
      'Poison': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 0.5,
        'Ground': 0.5,
        'Rock': 0.5,
        'Bug': 1,
        'Ghost': 0.5,
        'Steel': 0,
        'Fire': 1,
        'Water': 1,
        'Grass': 2,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 2
      },
      'Ground': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 0,
        'Poison': 2,
        'Ground': 1,
        'Rock': 2,
        'Bug': 0.5,
        'Ghost': 1,
        'Steel': 2,
        'Fire': 2,
        'Water': 1,
        'Grass': 0.5,
        'Electric': 2,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 1
      },
      'Rock': {
        'Normal': 1,
        'Fighting': 0.5,
        'Flying': 2,
        'Poison': 1,
        'Ground': 0.5,
        'Rock': 1,
        'Bug': 2,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 2,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 2,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 1
      },
      'Bug': {
        'Normal': 1,
        'Fighting': 0.5,
        'Flying': 0.5,
        'Poison': 0.5,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 0.5,
        'Steel': 0.5,
        'Fire': 0.5,
        'Water': 1,
        'Grass': 2,
        'Electric': 1,
        'Psychic': 2,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 2,
        'Fairy': 0.5
      },
      'Ghost': {
        'Normal': 0,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 2,
        'Steel': 1,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 2,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 0.5,
        'Fairy': 1
      },
      'Steel': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 2,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 0.5,
        'Water': 0.5,
        'Grass': 1,
        'Electric': 0.5,
        'Psychic': 1,
        'Ice': 2,
        'Dragon': 1,
        'Dark': 1,
        'Fairy': 2
      },
      'Fire': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 0.5,
        'Bug': 2,
        'Ghost': 1,
        'Steel': 2,
        'Fire': 0.5,
        'Water': 0.5,
        'Grass': 2,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 2,
        'Dragon': 0.5,
        'Dark': 1,
        'Fairy': 1
      },
      'Water': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 2,
        'Rock': 2,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 1,
        'Fire': 2,
        'Water': 0.5,
        'Grass': 0.5,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 0.5,
        'Dark': 1,
        'Fairy': 1
      },
      'Grass': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 0.5,
        'Poison': 0.5,
        'Ground': 2,
        'Rock': 2,
        'Bug': 0.5,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 0.5,
        'Water': 2,
        'Grass': 0.5,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 0.5,
        'Dark': 1,
        'Fairy': 1
      },
      'Electric': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 2,
        'Poison': 1,
        'Ground': 0,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 1,
        'Fire': 1,
        'Water': 2,
        'Grass': 0.5,
        'Electric': 0.5,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 0.5,
        'Dark': 1,
        'Fairy': 1
      },
      'Psychic': {
        'Normal': 1,
        'Fighting': 2,
        'Flying': 1,
        'Poison': 2,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 0.5,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 0,
        'Fairy': 1
      },
      'Ice': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 2,
        'Poison': 1,
        'Ground': 2,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 0.5,
        'Water': 0.5,
        'Grass': 2,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 0.5,
        'Dragon': 2,
        'Dark': 1,
        'Fairy': 1
      },
      'Dragon': {
        'Normal': 1,
        'Fighting': 1,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 2,
        'Dark': 1,
        'Fairy': 0
      },
      'Dark': {
        'Normal': 1,
        'Fighting': 0.5,
        'Flying': 1,
        'Poison': 1,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 2,
        'Steel': 1,
        'Fire': 1,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 2,
        'Ice': 1,
        'Dragon': 1,
        'Dark': 0.5,
        'Fairy': 0.5
      },
      'Fairy': {
        'Normal': 1,
        'Fighting': 2,
        'Flying': 1,
        'Poison': 0.5,
        'Ground': 1,
        'Rock': 1,
        'Bug': 1,
        'Ghost': 1,
        'Steel': 0.5,
        'Fire': 0.5,
        'Water': 1,
        'Grass': 1,
        'Electric': 1,
        'Psychic': 1,
        'Ice': 1,
        'Dragon': 2,
        'Dark': 2,
        'Fairy': 1
      }
    }
  
    addRow = function (table) {
      var row = document.createElement('tr');
      table.appendChild(row);
      return row;
    }
    addHead = function (title, row) {
      var col = document.createElement('th');
      col.appendChild(document.createTextNode(title));
      row.appendChild(col);
      return col;
    }
    addCol = function (modifier, row) {
      var col = document.createElement('td');
      switch (modifier) {
        case 0:
          col.className = 'zero';
          break;
        case 0.25:
          col.className = 'quarter';
          modifier = '¼';
          break;
        case 0.5:
          col.className = 'half';
          modifier = '½';
          break;
        case 2:
          col.className = 'double';
          break;
        case 4:
          col.className = 'quad';
          break;
      }
      col.appendChild(document.createTextNode(modifier));
      row.appendChild(col);
      return col;
    }
  
    createTable = function (chart, team) {
      var table, head, row, col, attackType, defenseType, modifier, pokemon;
      table = document.createElement('table');
      head = document.createElement('thead');
      table.appendChild(head);
      row = document.createElement('tr');
      head.appendChild(row);
      addHead('', row);
      for (attackType in chart) {
        addHead(attackType, row);
      }
      for (pokemon in team) {
        addHead(parseInt(pokemon)+1, row);
      }
      addHead('atk', row);
      addHead('def', row);
      // addHead('ave', row);
      for (attackType in chart) {
        row = addRow(table);
        col = document.createElement('th');
        col.appendChild(document.createTextNode(attackType));
        row.appendChild(col);
        for (defenseType in chart[attackType]) {
          modifier = chart[attackType][defenseType];
          addCol(modifier, row);
        }
  
        max = -1;
        min = 6;
        ave = 0;
        for (pokemon in team) {
          def1 = chart[attackType][team[pokemon].type1];
          def1 = (def1 != null ? def1 : 1);
          def2 = chart[attackType][team[pokemon].type2];
          def2 = (def2 != null ? def2 : 1);
          modifier = def1 * def2;
          atk1 = 0;
          atk2 = 0;
          if (team[pokemon].type1 != null)
            atk1 = chart[team[pokemon].type1][attackType];
          if (team[pokemon].type2 != null)
            atk2 = chart[team[pokemon].type2][attackType];
          if (team[pokemon].type1 != null || team[pokemon].type2 != null) {
            max = Math.max(atk1 || 0, atk2 || 0, max);
          }
          if (team[pokemon].type1 != null || team[pokemon].type2 != null) {
            min = Math.min(min, modifier);
          }
          ave += modifier;
          if (team[pokemon].type1 != null || team[pokemon].type2 != null) {
            addCol(modifier, row);
          } else {
            addCol('-', row);
          }
        }
        ave /= 6;
        ave = Math.round(ave*1000)/1000;
        if (max === -1) {
          addCol('-', row);
        } else {
          addCol(max, row);
        }
        if (min === 6) {
          addCol('-', row);
        } else {
          addCol(min, row);
        }
  
        // addCol(ave, row);
      }
      return table;
    }
  
    createForm = function (chart, pokedex) {
      var index, poketype, type, form, datalist, fieldset, legend, select, option, input, pokeindex, pokemon;
      form = document.createElement('form');
      datalist = document.createElement('datalist');
      datalist.setAttribute('id', 'pokedex');
      for (pokeindex in pokedex) {
        pokemon = pokedex[pokeindex];
        option = document.createElement('option');
        option.setAttribute('value', pokemon.name);
        // option.appendChild(document.createTextNode(pokemon.name));
        datalist.appendChild(option);
      }
      form.appendChild(datalist);
      for (index = 0; index < 6; index++) {
        fieldset = document.createElement('fieldset');
        form.appendChild(fieldset);
        legend = document.createElement('legend');
        legend.appendChild(document.createTextNode('Pokemon '+(index+1)));
        fieldset.appendChild(legend);
        for (poketype = 0; poketype < 2; poketype++) {
          select = document.createElement('select');
          select.setAttribute('name', (index+1)+'-'+(poketype+1));
          select.setAttribute('class', 'type'+(poketype+1));
          fieldset.appendChild(select);
          select.addEventListener('change', change.bind(this, select, index, poketype));
          option = document.createElement('option');
          option.setAttribute('value', '');
          option.appendChild(document.createTextNode('type ' + (poketype+1)));
          select.appendChild(option);
          for (type in chart) {
            option = document.createElement('option');
            option.setAttribute('value', type);
            option.appendChild(document.createTextNode(type));
            select.appendChild(option);
          }
        }
        input = document.createElement('input');
        input.setAttribute('list', 'pokedex');
        input.setAttribute('type', 'text');
        input.setAttribute('placeholder', 'name');
        input.addEventListener('input', search.bind(this, input, index));
        fieldset.appendChild(input);
      }
      return form;
    }
  
    change = function (element, pokemon, type, event) {
      team[pokemon]['type'+(type+1)] = element.value || null;
      table = createTable(chart, team);
      body = document.getElementsByTagName('body')[0];
      body.replaceChild(table, body.getElementsByTagName('table')[0]);
    }
  
    search = function(element, teamIndex, event) {
      var name = element.value;
      pokemon = pokedex.filter(function (pokemon) {
        return pokemon.name === name;
      })[0];
      if (pokemon == null) {
        return;
      }
      type1 = team[teamIndex].type1 = pokemon.type1 || null;
      type2 = team[teamIndex].type2 = pokemon.type2 || null;
      if (type1) {
        element.parentElement.querySelector('.type1').value = type1;
      } else {
        element.parentElement.querySelector('.type1').value = '';
      }
      if (type2) {
        element.parentElement.querySelector('.type2').value = type2;
      } else {
        element.parentElement.querySelector('.type2').value = '';
      }
      table = createTable(chart, team);
      body = document.getElementsByTagName('body')[0];
      body.replaceChild(table, body.getElementsByTagName('table')[0]);
    }
  
    team = [];
    for (index = 0; index < 6; index++) {
      team[index] = {type1: null, type2: null};
    }
  
    body = document.querySelector('body');
    table = createTable(chart, team);
    body.replaceChild(table, document.querySelector('table'));
  
    form = createForm(chart, pokedex);
    body.replaceChild(form, document.querySelector('form'));
  }());
  